In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
from pathlib import Path
import subprocess

from astropy.io import fits

# Accessing Reduced SpeX data (thru the index.html)
Hi! This notebook will showcase my (Evan) work in trying to access the info on an object after being reduced with pyspextools! 

From quick inspection of some already reduced data, it seems finished data will output an index.html file that holds a lot of an objects info (in the qa directory).

That makes my life a lot easier! So my main goals then will be:
- Access that data with a python function
- Store that data in a table (Final storage / structure can be optimized, just need to be able to store it somewhere)
- Make a front to back function / script to do this for multiple files!

In [ ]:
# Just gonna set this global vartiable so I can grab later!
REDUCTIONS_DIR = Path("reductions")

MOVING_PS_DF = pd.DataFrame()
FIXED_PS_DF = pd.DataFrame()

for redux_dir in REDUCTIONS_DIR.iterdir():
    # EX_DATA = Path(f"{REDUCTIONS_DIR}/20010312-1")
    INDEX_PATH = Path(f"{redux_dir}/qa/index.html")

    with open(INDEX_PATH) as f:
        lines = f.readlines()

    for i, line in enumerate(lines):
        if "Source Name" in line:

            if "moving-ps" in line:

                _info_dict = {
                "OBSERVATION_FOLDER" : str(EX_DATA).split("/")[-1],
                "SOURCE NAME" : line.strip("   <li> Source Name:").split(" (moving-ps)")[0],
                "COORDINATES" : lines[i+1].strip("    <li>Coordinate: ").rstrip(" \n")
                }

                MOVING_PS_DF = pd.concat([MOVING_PS_DF, pd.DataFrame([_info_dict])])


            elif "fixed-ps" in line:

                _info_dict = {
                "OBSERVATION_FOLDER" : str(EX_DATA).split("/")[-1],
                "SOURCE NAME" : line.strip("   <li> Source Name:").split(" (fixed-ps)")[0],
                "COORDINATES" : lines[i+1].strip("    <li>Coordinate: ").split(" [<a href=")[0]
                }

                FIXED_PS_DF = pd.concat([FIXED_PS_DF, pd.DataFrame([_info_dict])])

            else:
                print(f"SOMETHING WENT WRONG WITH LINE {i}")

print(MOVING_PS_DF)
FIXED_PS_DF

   OBSERVATION_FOLDER      SOURCE NAME  \
0          20010312-1        1999 NV27
0          20010312-1        Keet Seel
0          20010312-1          1994 CO
0          20010312-1    824 Anastasia
0          20010312-1          44 Nysa
..                ...              ...
0          20010312-1        2001 SG10
0          20010312-1       719 Albert
0          20010312-1  1904 Massevitch
0          20010312-1        1998 SF36
0          20010312-1     4159 Freeman

                                         COORDINATES
0         23:49:47.03 +17:40:36.8 at MJD 52175.28398
0         00:34:56.64 +13:58:35.1 at MJD 52175.36545
0          00:54:33.2 -03:30:50.8 at MJD 52175.39984
0         19:24:44.44 -20:29:49.2 at MJD 52181.20912
0         19:44:29.05 -21:29:36.9 at MJD 52181.22912
..                                               ...
0         00:52:11.45 +00:56:52.6 at MJD 52188.42046
0         02:43:04.75 +03:46:55.2 at MJD 52188.55069
0         04:51:38.06 +08:28:42.4 at MJD 52188.62252
0   13:05:54.98 +17:49:30.3 at MJD 51980.44598934726
0   13:22:10.47 +16:27:37.4 at MJD 51980.60103788047

[103 rows x 3 columns]

  OBSERVATION_FOLDER     SOURCE NAME              COORDINATES
0         20010312-1         66 Maja  03:36:07.39 +21:39:16.7
0         20010312-1         4 Vesta  04:50:32.01 +15:10:59.3
0         20010312-1             673  14:07:35.03 -12:35:37.5
0         20010312-1            1350  21:42:46.14 -12:45:59.1
0         20010312-1        HD214558  22:38:18.02 +45:10:55.5
0         20010312-1         Ennomos  03:31:48.41 +32:13:29.6
0         20010312-1          HD 489  00:09:28.41 +19:06:58.3
0         20010312-1       sao 98291  09:01:03.49 +12:32:36.4
0         20010312-1  446 Aeternitas   22:25:14.6 -25:09:23.3
0         20010312-1        AO128191  23:27:20.97 +04:27:03.3
0         20010312-1       1086 Nata  03:27:56.85 +30:03:25.9
0         20010312-1        HD142557  18:43:51.33 -06:49:08.9
0         20010312-1        1989 TS1  01:02:37.63 +13:00:43.4
0         20010312-1   349 Dembowska    21:21:07.86 -25:20:51

# Accessing Reductions (thru .fits files)

Post-Week 2 Meeting, I learned that info on the object can also be found in the headers of the spectra's .fits files
_THATS REAL AWKWARD_

That means the index files are really needed? Although I guess it was a nice exercise in a way--knowing I could read thru a file with python via path commands!

In [3]:
hdu = fits.open("/Users/epritchard/Research/CSL_Summer_2026/SpeX_Summer_2026/combined/spex-prism_2M-1000+32_2030201001_2009B069_178-197comb.fits")
h = hdu[0].header
hdu.close()
print(h)

SIMPLE  =                    T / conforms to FITS standard                      BITPIX  =                  -64 / array data type                                NAXIS   =                    3 / number of array dimensions                     NAXIS1  =                  563                                                  NAXIS2  =                    4                                                  NAXIS3  =                    1                                                  DIVISOR =                   32 / Normalization value                            ORIGIN  = 'Institute for Astronomy'                                             TELESCOP= 'NASA IRTF'                                                           OBSERVER= 'Your_Name'                                                           PROG_ID =                                                                       OBJECT  = '2M 1000+32'                                                          NDR     =                   32 / Number of Non-Destructive Reads                SRT_AM  =                1.143 / Start airmass                                  AVE_AM  =                1.098 / Average airmass                                END_AM  =                1.059 / End airmass                                    SRT_HA  = '-01:57:08.29'       / Start hour angle (hours)                       AVE_HA  = '-01:31:55.66'       / Average hour angle (hours)                     END_HA  = '-01:05:22.83'       / End hour angle (hours)                         PA      =               255.47 / Position Angle E of N (deg)                    RA      = '+10:00:17.09'       / Right Ascension                                DEC     = '++32:18:30.9'       / Declination                                    ITIME   =                120.0 / Integration time (sec)                         NCOADDS =                    1 / Number of COADDS                               IMGITIME=                120.0 / Image integration time, NCOADDSxITIME (sec)    TOTITIME=               2160.0 / Total integration time (sec)                   SRT_TIME= '09:45:14.619810'    / Start observations time in UTC                 AVE_TIME= '10:10:23.45'        / Average observation time in UTC                END_TIME= '10:36:52.170515'    / End observation time in UTC                    SRT_DATE= '2010-01-30'         / Start observations date in UTC                 AVE_DATE= '2010-01-30'         / Average observation date in UTC                END_DATE= '2010-01-30'         / End observation date in UTC                    SRT_MJD =    55226.40641921076 / Start Modified Julian Date                     AVE_MJD =    55226.42388246566 / Average Modified Julian Date                   END_MJD =    55226.44227049207 / End Modified Julian Date                       FILENAME= 'calspec178-197.fits' / File name                                     MODE    = 'LowRes15'           / Instrument Mode                                INSTR   = 'SpeX    '           / Instrument                                     MODULE  = 'telluric'           / Creation module                                VERSION = '1.2b4   '           / pySpextool version                             FLAT    = 'flat172-177.fits'   / Flat field image                               WAVECAL = 'wavecal172-177.fits' / Wavecal file                                  WCTYPE  = '1D      '           / Wavelength calibration type                    WAVETYPE= 'vacuum  '           / Wavelength type                                NORDERS =                    1 / Number of orders                               ORDERS  = '1       '           / Orders                                         NAPS    =                    1 / Number of apertures                            PLTSCALE=                 0.15 / Plate scale (arcseconds pixel-1)               SLTH_ARC=                 15.0 / Nominal slit height (arcseconds)               SLTW_ARC=                  0.5 / Slit width (arcseconds)                        SLTH_PIX=                100.0 / Nominal slit height (pixels)                   SLTW_PIX=                  3.3 / Slit width (pixels)                            RP      =                  200 / Average resolving power                        BDPXFIX =                    F / Bad pixels fixed?                              THRESH  =                    7 / Bad pixel sigma threshold                      OPTEXT  =                    T / Optimal extraction?                            SUMEXT  =                    F / Sum extraction?                                PSFRAD  =                  1.5 / PSF radius (arcseconds)                        APRADII =                                                                       XUNITS  = 'um      '           / Units of the x axis                            YUNITS  = 'W m-2 um-1'         / Units of the y axis                            LXUNITS = '$\mu$m  '           / LateX units of the x axis                      LYUNITS = '(W m$^{-2}$ $\mu$m$^{-1}$)' / LateX units of the y axis              LXLABEL = 'Wavelength ($\mu$m)' / LateX x-axis label                            LYLABEL = '$f_\lambda$(W m$^{-2}$ $\mu$m$^{-1}$)' / LateX y-axis flux label     LULABEL = '$\sigma$(W m$^{-2}$ $\mu$m$^{-1}$)' / LateX y-axis uncertainty label CMB_NFL =                   18 / Number of spectra files combined               CMB_NAP =                    0 / Number of apertures combined                   CMB_STAT= 'robust weighted mean' / Combination statistic                        CMB_THSH=                    8 / Combination robust threshold (if used)         TC_OFILE= 'combspec178-197.fits' / Telluric object input file                   TC_SFILE= 'combspec198-207.fits' / Telluric standard input file                 TC_STDID= 'HD 89239'           / Telluric standard                              TC_STDST= 'A2VmB9.5p_lB'       / Telluric spectral type                         TC_STDT =                 8800 / Telluric effective temperature (K)             TC_STDB =                6.498 / Telluric standard B mag                        TC_STDV =                6.523 / Telluric standard V mag                        TC_STDRV=                  0.0 / Telluric standard radial velocity (km s-1)     TC_DAM  =                 0.04 / Telluric Average airmass difference            TC_DAN  =                 6.25 / Telluric angular separation (deg) of obj and stTC_TYPE = 'A0V     '           / Telluric correction type                       TC_METH = 'ip      '           / Kernel creation method                         TC_SO001= '-0.34   '           / Standard shift (pixels) for order 001          HISTORY Spextool FITS files contain an array of size                            HISTORY [nwaves,4,norders*naps]. The ith image (array[*,*,i]) contains          HISTORY the data for a single extraction aperture within an order such          HISTORY that, lambda=array[*,0,i], flux=array[*,1,i],                           HISTORY uncertainty=array[*,2,i],flag=array[*,3,i].  The zeroth image           HISTORY (array[*,*,0]) contains the data for the aperture in the order          HISTORY closest to the bottom of the detector that is closest to the            HISTORY bottom of the slit (i.e. also closest to the bottom of the              HISTORY detector).  Moving up the detector, the FITS array is filled in         HISTORY with subsequent extraction apertures.  If no orders have been           HISTORY deselected in the extraction process, the contents of the ith           HISTORY aperture in order j can be found as follows:                            HISTORY lambda=array[*,0,{j-min(orders)}*naps + (i-1)],                         HISTORY flux=array[*,1,{j-min(orders)}*naps + (i-1)],                           HISTORY uncertainty=array[*,2,{j-min(orders)}*naps + (i-1)],                    HISTORY flag=array[*,3,{j-min(orders)}*naps + (i-1)].                           HISTORY                                                                         HISTORY The spectra in the file(s) spectra0178.fits, spectra0179.fits,          HISTORY spectra0180.fits, spectra0181.fits, spectra0182.fits,                   HISTORY spectra0183.fits, spectra0184.fits, spectra0185.fits,                   HISTORY spectra0186.fits, spectra0187.fits, spectra0190.fits,                   HISTORY spectra0191.fits, spectra0192.fits, spectra0193.fits,                   HISTORY spectra0194.fits, spectra0195.fits, spectra0196.fits,                   HISTORY spectra0197.fits were combined using a robust weighted mean             HISTORY with a sigma threshold of 8.  Aperture 1 modifications: The             HISTORY scale factors were determined using order 1 and are:                    HISTORY 1.497101370767507, 0.990116193841449, 0.9340852629539408,               HISTORY 1.0302847102875954, 0.8952145173030188, 1.0338076675918713,             HISTORY 1.0036195168561708, 1.0031730077338188, 0.9735751896317318,             HISTORY 1.0956488353873952, 0.8836208726015873, 1.0430673153508654,             HISTORY 0.8521350951403067, 1.1235800890097452, 0.995790145460822,              HISTORY 1.1598790761453623, 0.9968470012450493, 0.9880621938640075.             END

In [ ]:
hdu = fits.open("/Users/epritchard/Research/CSL_Summer_2026/SpeX_Summer_2026/reductions/20010621-1/proc/combspec1022-1037.fits")
h = hdu[0].header
hdu.close()
print(h)

SIMPLE  =                    T / conforms to FITS standard                      BITPIX  =                  -64 / array data type                                NAXIS   =                    3 / number of array dimensions                     NAXIS1  =                  563                                                  NAXIS2  =                    4                                                  NAXIS3  =                    1                                                  DIVISOR =                   32 / Normalization value                            ORIGIN  = 'Institute for Astronomy'                                             TELESCOP= 'NASA IRTF'                                                           OBSERVER= 'Bus     '                                                            OBJECT  = '1999 KW4'                                                            BEAM    = 'A       '           / Object(A) or sky(B)                            CYCLES  =                    5 / Number of cycles                               NDR     =                   32 / Number of Non-Destructive Reads                TABLE_MS=              512.452 / msec to clock out array                        GFLT    = 'J       '           / menu=2,pos=106666                              SRT_AM  =                1.023 / Start airmass                                  AVE_AM  = '1.038   '           / Average airmass                                END_AM  =                1.057 / End airmass                                    SRT_HA  = '+00:39:35.32'       / Start hour angle (hours)                       AVE_HA  = '+00:57:18.33'       / Average hour angle (hours)                     END_HA  = '+01:15:06.79'       / End hour angle (hours)                         PA      =                  0.0 / Position Angle E of N (deg)                    RA      = '13:14:56.26'        / Right Ascension                                DEC     = '+27:55:02.0'        / Declination                                    ITIME   =                120.0 / Integration time (sec)                         NCOADDS =                    1 / Number of COADDS                               IMGITIME=                120.0 / Image integration time, NCOADDSxITIME (sec)    TOTITIME=               1920.0 / Total integration time (sec)                   SRT_TIME= '06:16:04.908332'    / Start observations time in UTC                 AVE_TIME= '+06:33:44.31'       / Average observation time in UTC                END_TIME= '06:51:29.323761'    / End observation time in UTC                    SRT_DATE= '2001-06-21'         / Start observations date in UTC                 AVE_DATE= '2001-06-21'         / Average observation date in UTC                END_DATE= '2001-06-21'         / End observation date in UTC                    SRT_MJD =    52081.26116792051 / Start modified Julian date                     AVE_MJD = '52081.27342953412'  / Average modified Julian date                   END_MJD =    52081.28575606205 / End airmass                                    FILENAME= 'combspec1022-1037.fits' / File name                                  MODE    = 'LowRes15'           / Instrument Mode                                INSTR   = 'SpeX    '           / Instrument                                     USERCOM = '.       '           / User comment                                   MODULE  = 'combine '           / Creation module                                VERSION = '1beta   '           / pySpextool version                             AIMAGE  = 'sp6.1022.a.fits'    / A image                                        SKYORDRK= 'sp6.1023.b.fits'    / Sky or dark image                              FLAT    = 'flat1001-1021.fits' / Flat field image                               WAVECAL = 'wavecal1001-1021.fits' / Wavecal file                                WCTYPE  =                    1 / Wavelength calibration type                    WAVETYPE= 'vacuum  '           / Wavelength type                                NORDERS =                    1 / Number of orders                               ORDERS  = '1       '           / Orders                                         NAPS    =                    1 / Number of apertures                            PLTSCALE=                 0.15 / Plate scale (arcseconds pixel-1)               SLTH_ARC=                 15.0 / Nominal slit height (arcseconds)               SLTW_ARC=                  0.8 / Slit width (arcseconds)                        SLTH_PIX=                100.0 / Nominal slit height (pixels)                   SLTW_PIX=    5.333333333333334 / Slit width (pixels)                            RP      =   123.74999999999999 / Average resolving power                        BDPXFIX =                    F / Bad pixels fixed?                              THRESH  =                    7 / Bad pixel sigma threshold                      OPTEXT  =                    T / Optimal extraction?                            SUMEXT  =                    F / Sum extraction?                                PSFRAD  =                  1.5 / PSF radius (arcseconds)                        APRADII =                  1.5 / Aperture radii (arcseconds)                    XUNITS  = 'um      '           / Units of the x axis                            YUNITS  = 'DN s-1  '           / Units of the y axis                            LXUNITS = '$\mu$m  '           / LateX units of the x axis                      LYUNITS = 'DN s$^{-1}$'        / LateX units of the y axis                      LXLABEL = 'Wavelength ($\mu$m)' / LateX x axis label                            LYLABEL = 'Count Rate (DN s$^{-1}$)' / LateX Y axis label                       NFLCOMB =                   16 /  Number of spectra files combined              NAPCOMB =                    0 /  Number of apertures combined                  COMBSTAT= 'robust weighted mean' /  Combination statistic                       RBTHRESH=                    8 /  Robust threshold (if used)                    HISTORY Spextool FITS files contain an array of size                            HISTORY [nwaves,4,norders*naps]. The ith image (array[*,*,i]) contains          HISTORY the data for a single extraction aperture within an order such          HISTORY that, lambda=array[*,0,i], flux=array[*,1,i],                           HISTORY uncertainty=array[*,2,i],flag=array[*,3,i].  The zeroth image           HISTORY (array[*,*,0]) contains the data for the aperture in the order          HISTORY closest to the bottom of the detector that is closest to the            HISTORY bottom of the slit (i.e. also closest to the bottom of the              HISTORY detector).  Moving up the detector, the FITS array is filled in         HISTORY with subsequent extraction apertures.  If no orders have been           HISTORY deselected in the extraction process, the contents of the ith           HISTORY aperture in order j can be found as follows:                            HISTORY lambda=array[*,0,{j-min(orders)}*naps + (i-1)],                         HISTORY flux=array[*,1,{j-min(orders)}*naps + (i-1)],                           HISTORY uncertainty=array[*,2,{j-min(orders)}*naps + (i-1)],                    HISTORY flag=array[*,3,{j-min(orders)}*naps + (i-1)].                           HISTORY                                                                         HISTORY The spectra in the file(s) spectra1022.fits, spectra1023.fits,          HISTORY spectra1024.fits, spectra1025.fits, spectra1026.fits,                   HISTORY spectra1027.fits, spectra1028.fits, spectra1029.fits,                   HISTORY spectra1030.fits, spectra1031.fits, spectra1032.fits,                   HISTORY spectra1033.fits, spectra1034.fits, spectra1035.fits,                   HISTORY spectra1036.fits, spectra1037.fits were combined using a robust         HISTORY weighted mean with a sigma threshold of 8.  Aperture 1                  HISTORY modifications: The scale factors were determined using order 1          HISTORY and are: 1.010335016811289, 0.9492107340730178,                         HISTORY 0.9930874271300736, 0.9218272948849491, 0.9300468176940382,             HISTORY 0.9885351965315253, 0.975728641707654, 0.9748364789223939,              HISTORY 1.0070094799518208, 0.9620545061076332, 1.051875616969182,              HISTORY 1.106022362826651, 1.077798945037372, 1.1429913251474741,               HISTORY 1.2560251615997648, 1.3255995398856137.                                 END

In [5]:
hdu = fits.open("/Users/epritchard/Research/CSL_Summer_2026/SpeX_Summer_2026/combined/spex-prism_AUR-165_2012201011_2010B106_161-170comb.fits")
h = hdu[0].header
hdu.close()
print(h)

SIMPLE  =                    T / conforms to FITS standard                      BITPIX  =                  -64 / array data type                                NAXIS   =                    3 / number of array dimensions                     NAXIS1  =                  563                                                  NAXIS2  =                    4                                                  NAXIS3  =                    1                                                  DIVISOR =                   32 / Normalization value                            ORIGIN  = 'Institute for Astronomy'                                             TELESCOP= 'NASA IRTF'                                                           OBSERVER= 'Peterson'                                                            PROG_ID =                                                                       OBJECT  = 'AUR-165 '                                                            NDR     =                   32 / Number of Non-Destructive Reads                SRT_AM  =                1.609 / Start airmass                                  AVE_AM  =                1.643 / Average airmass                                END_AM  =                1.677 / End airmass                                    SRT_HA  = '++03:45:38.24'      / Start hour angle (hours)                       AVE_HA  = '+03:50:08.52'       / Average hour angle (hours)                     END_HA  = '++03:54:38.66'      / End hour angle (hours)                         PA      =                 92.4 / Position Angle E of N (deg)                    RA      = '+04:30:24.85'       / Right Ascension                                DEC     = '++35:43:17.4'       / Declination                                    ITIME   =                 40.0 / Integration time (sec)                         NCOADDS =                    1 / Number of COADDS                               IMGITIME=                 40.0 / Image integration time, NCOADDSxITIME (sec)    TOTITIME=                400.0 / Total integration time (sec)                   SRT_TIME= '15:11:17.452148'    / Start observations time in UTC                 AVE_TIME= '15:15:47.51'        / Average observation time in UTC                END_TIME= '15:20:17.420786'    / End observation time in UTC                    SRT_DATE= '2010-11-12'         / Start observations date in UTC                 AVE_DATE= '2010-11-12'         / Average observation date in UTC                END_DATE= '2010-11-12'         / End observation date in UTC                    SRT_MJD =    55512.63284088134 / Start Modified Julian Date                     AVE_MJD =    55512.63596656286 / Average Modified Julian Date                   END_MJD =    55512.63909051836 / End Modified Julian Date                       FILENAME= 'calspec161-170.fits' / File name                                     MODE    = 'LowRes15'           / Instrument Mode                                INSTR   = 'SpeX    '           / Instrument                                     MODULE  = 'telluric'           / Creation module                                VERSION = '1.5b3   '           / pySpextool version                             FLAT    = 'flat155-160.fits'   / Flat field image                               WAVECAL = 'wavecal155-160.fits' / Wavecal file                                  WCTYPE  = '1D      '           / Wavelength calibration type                    WAVETYPE= 'vacuum  '           / Wavelength type                                NORDERS =                    1 / Number of orders                               ORDERS  = '1       '           / Orders                                         NAPS    =                    1 / Number of apertures                            PLTSCALE=                 0.15 / Plate scale (arcseconds pixel-1)               SLTH_ARC=                 15.0 / Nominal slit height (arcseconds)               SLTW_ARC=                  0.5 / Slit width (arcseconds)                        SLTH_PIX=                100.0 / Nominal slit height (pixels)                   SLTW_PIX=                  3.3 / Slit width (pixels)                            RP      =                  200 / Average resolving power                        BDPXFIX =                    F / Bad pixels fixed?                              THRESH  =                    7 / Bad pixel sigma threshold                      OPTEXT  =                    T / Optimal extraction?                            SUMEXT  =                    F / Sum extraction?                                PSFRAD  =                  1.5 / PSF radius (arcseconds)                        APRADII =                                                                       XUNITS  = 'um      '           / Units of the x axis                            YUNITS  = 'W m-2 um-1'         / Units of the y axis                            LXUNITS = '$\mu$m  '           / LateX units of the x axis                      LYUNITS = '(W m$^{-2}$ $\mu$m$^{-1}$)' / LateX units of the y axis              LXLABEL = 'Wavelength ($\mu$m)' / LateX x-axis label                            LYLABEL = '$f_\lambda$(W m$^{-2}$ $\mu$m$^{-1}$)' / LateX y-axis flux label     LULABEL = '$\sigma$(W m$^{-2}$ $\mu$m$^{-1}$)' / LateX y-axis uncertainty label CMB_NFL =                   10 / Number of spectra files combined               CMB_NAP =                    0 / Number of apertures combined                   CMB_STAT= 'robust weighted mean' / Combination statistic                        CMB_THSH=                    8 / Combination robust threshold (if used)         TC_OFILE= 'combspec161-170.fits' / Telluric object input file                   TC_SFILE= 'combspec171-180.fits' / Telluric standard input file                 TC_STDID= 'HD282141'           / Telluric standard                              TC_STDST= 'A2      '           / Telluric spectral type                         TC_STDT =                 8800 / Telluric effective temperature (K)             TC_STDB =                 11.3 / Telluric standard B mag                        TC_STDV =                10.71 / Telluric standard V mag                        TC_STDRV=                  0.0 / Telluric standard radial velocity (km s-1)     TC_DAM  =                 -0.1 / Telluric Average airmass difference            TC_DAN  =                 4.36 / Telluric angular separation (deg) of obj and stTC_TYPE = 'A0V     '           / Telluric correction type                       TC_METH = 'ip      '           / Kernel creation method                         TC_SO001= '-0.02   '           / Standard shift (pixels) for order 001          SNRO001 = '3440    '           /  Median S/N values for order 001               HISTORY Spextool FITS files contain an array of size                            HISTORY [nwaves,4,norders*naps]. The ith image (array[*,*,i]) contains          HISTORY the data for a single extraction aperture within an order such          HISTORY that, lambda=array[*,0,i], flux=array[*,1,i],                           HISTORY uncertainty=array[*,2,i],flag=array[*,3,i].  The zeroth image           HISTORY (array[*,*,0]) contains the data for the aperture in the order          HISTORY closest to the bottom of the detector that is closest to the            HISTORY bottom of the slit (i.e. also closest to the bottom of the              HISTORY detector).  Moving up the detector, the FITS array is filled in         HISTORY with subsequent extraction apertures.  If no orders have been           HISTORY deselected in the extraction process, the contents of the ith           HISTORY aperture in order j can be found as follows:                            HISTORY lambda=array[*,0,{j-min(orders)}*naps + (i-1)],                         HISTORY flux=array[*,1,{j-min(orders)}*naps + (i-1)],                           HISTORY uncertainty=array[*,2,{j-min(orders)}*naps + (i-1)],                    HISTORY flag=array[*,3,{j-min(orders)}*naps + (i-1)].                           HISTORY                                                                         HISTORY The spectra in the file(s) spectra0161.fits, spectra0162.fits,          HISTORY spectra0163.fits, spectra0164.fits, spectra0165.fits,                   HISTORY spectra0166.fits, spectra0167.fits, spectra0168.fits,                   HISTORY spectra0169.fits, spectra0170.fits were combined using a robust         HISTORY weighted mean with a sigma threshold of 8.  Aperture 1                  HISTORY modifications: The scale factors were determined using order 1          HISTORY and are: 1.0003095029310018, 0.9586638444899852,                        HISTORY 0.9246748782876215, 0.9889883009430808, 1.0621601732453025,             HISTORY 1.1156601455501018, 1.0029321331657217, 0.9996906885346084,             HISTORY 1.1977869947839987, 0.9101759772897443.                                 END

In [6]:
hdu = fits.open("/Users/epritchard/Research/CSL_Summer_2026/SpeX_Summer_2026/combined/spex-prism_WISE-0714-1212_20101218_2010B095_53-58.fits")
h = hdu[0].header
hdu.close()
print(h)

SIMPLE  =                    T / conforms to FITS standard                      BITPIX  =                  -64 / array data type                                NAXIS   =                    3 / number of array dimensions                     NAXIS1  =                  563                                                  NAXIS2  =                    4                                                  NAXIS3  =                    1                                                  DIVISOR =                   32 / Normalization value                            ORIGIN  = 'Institute for Astronomy'                                             TELESCOP= 'NASA IRTF'                                                           OBSERVER= 'Your_Name'                                                           PROG_ID =                                                                       OBJECT  = 'WISE 0714-1212'                                                      TABLE_MS=              512.452 / msec to clock out array                        GFLT    = 'J       '           / menu=2,pos=106666                              SLIT    = '0.5x15  '           / menu=3,pos=121000                              SRT_AM  =                1.232 / Start airmass                                  AVE_AM  =                1.247 / Average airmass                                END_AM  =                1.264 / End airmass                                    SRT_HA  = '++01:04:21.68'      / Start hour angle (hours)                       AVE_HA  = '+01:12:43.40'       / Average hour angle (hours)                     END_HA  = '++01:21:05.01'      / End hour angle (hours)                         PA      =                77.59 / Position Angle E of N (deg)                    RA      = '+07:14:28.64'       / Right Ascension                                DEC     = '-12:12:34.4'        / Declination                                    ITIME   =                180.0 / Integration time (sec)                         NCOADDS =                    1 / Number of COADDS                               IMGITIME=                180.0 / Image integration time, NCOADDSxITIME (sec)    TOTITIME=               1080.0 / Total integration time (sec)                   SRT_TIME= '12:49:53.669926'    / Start observations time in UTC                 AVE_TIME= '12:58:14.44'        / Average observation time in UTC                END_TIME= '13:06:35.116566'    / End observation time in UTC                    SRT_DATE= '2010-12-18'         / Start observations date in UTC                 AVE_DATE= '2010-12-18'         / Average observation date in UTC                END_DATE= '2010-12-18'         / End observation date in UTC                    SRT_MJD =    55548.53464895748 / Start Modified Julian Date                     AVE_MJD =    55548.54044491242 / Average Modified Julian Date                   END_MJD =    55548.54623977507 / End Modified Julian Date                       FILENAME= 'calspec53-58.fits'  / File name                                      MODE    = 'LowRes15'           / Instrument Mode                                INSTR   = 'SpeX    '           / Instrument                                     USERCOM = 'FITS_Header_Comment' / User comment                                  MODULE  = 'telluric'           / Creation module                                VERSION = '1.6b3   '           / pySpextool version                             AIMAGE  = 'filename0053.a.fits' / A image                                       SKYORDRK= 'filename0054.b.fits' / Sky or dark image                             FLAT    = 'flat47-52.fits'     / Flat field image                               FLFIELD =                    T / Flat fielded?                                  WAVECAL = 'wavecal47-52.fits'  / Wavecal file                                   WCTYPE  = '1D      '           / Wavelength calibration type                    WAVETYPE= 'vacuum  '           / Wavelength type                                NORDERS =                    1 / Number of orders                               ORDERS  = '1       '           / Orders                                         NAPS    =                    1 / Number of apertures                            PLTSCALE=                 0.15 / Plate scale (arcseconds pixel-1)               SLTH_ARC=                 15.0 / Nominal slit height (arcseconds)               SLTW_ARC=                  0.5 / Slit width (arcseconds)                        SLTH_PIX=                100.0 / Nominal slit height (pixels)                   SLTW_PIX=                  3.3 / Slit width (pixels)                            RP      =                  200 / Average resolving power                        APOSO001= '3.7003,11.5171'     / Aperture positions (arcseconds) for order 001  ARADO001= '1.5,1.5 '           / Aperture radii (arcseconds) for order 001      BGSUB   =                    T / Background subtraction?                        BGREGS  =  / Background regions (arcseconds)                                    BGSTART =                  2.5 / Background annulus start (arcseconds)          BGWIDTH =                  4.0 / Background annulus width (arcseconds)          BGFITDEG=                    0 / Background fit degree                          BDPXFIX =                    F / Bad pixels fixed?                              THRESH  =                    7 / Bad pixel sigma threshold                      OPTEXT  =                    T / Optimal extraction?                            SUMEXT  =                    F / Sum extraction?                                PSFRAD  =                  1.5 / PSF radius (arcseconds)                        SNRO001 = '217     '           /  Median S/N for order 001                      XUNITS  = 'um      '           / Units of the x axis                            YUNITS  = 'DN s-1  '           / Units of the y axis                            LXUNITS = '$\mu$m  '           / LateX units of the x axis                      LYUNITS = 'W m$^{-2}$ $\mu$m$^{-1}$' / LateX units of the y axis                LXLABEL = 'Wavelength ($\mu$m)' / LateX x-axis label                            LYLABEL = '$f_\lambda$(W m$^{-2}$ $\mu$m$^{-1}$)' / LateX y-axis flux label     LULABEL = '$\sigma$(W m$^{-2}$ $\mu$m$^{-1}$)' / LateX y-axis uncertainty label CMB_NFL =                    6 / Number of spectra files combined               CMB_NAP =                    0 / Number of apertures combined                   CMB_STAT= 'robust weighted mean' / Combination statistic                        CMB_THSH=                    8 / Combination robust threshold (if used)         TC_SFILE= 'combspec59-70.fits' / Telluric standard input file                   TC_STDID= 'HD 56525'           / Telluric standard                              TC_STDST= 'A0V     '           / Telluric standard spectral type                TC_TYPE = 'A0V     '           / Telluric correction type                       TC_METH = 'ip      '           / Kernel creation method                         HISTORY Spextool FITS files contain an array of size                            HISTORY [nwaves,4,norders*naps]. The ith image (array[*,*,i]) contains          HISTORY the data for a single extraction aperture within an order such          HISTORY that, lambda=array[*,0,i], flux=array[*,1,i],                           HISTORY uncertainty=array[*,2,i],flag=array[*,3,i].  The zeroth image           HISTORY (array[*,*,0]) contains the data for the aperture in the order          HISTORY closest to the bottom of the detector that is closest to the            HISTORY bottom of the slit (i.e. also closest to the bottom of the              HISTORY detector).  Moving up the detector, the FITS array is filled in         HISTORY with subsequent extraction apertures.  If no orders have been           HISTORY deselected in the extraction process, the contents of the ith           HISTORY aperture in order j can be found as follows:                            HISTORY lambda=array[*,0,{j-min(orders)}*naps + (i-1)],                         HISTORY flux=array[*,1,{j-min(orders)}*naps + (i-1)],                           HISTORY uncertainty=array[*,2,{j-min(orders)}*naps + (i-1)],                    HISTORY flag=array[*,3,{j-min(orders)}*naps + (i-1)].                           HISTORY                                                                         HISTORY The spectra in the file(s) spectra0053.fits, spectra0054.fits,          HISTORY spectra0055.fits, spectra0056.fits, spectra0057.fits,                   HISTORY spectra0058.fits were combined using a robust weighted mean             HISTORY with a sigma threshold of 8.  Aperture 1 modifications: The             HISTORY scale factors were determined using order 1 and are:                    HISTORY 1.396067265286368, 0.8853986551337285, 0.8825932727616671,              HISTORY 0.9107106411563612, 1.1087010536082573, 1.45500000387034.               END

In [7]:
hdu = fits.open("/Users/epritchard/Research/CSL_Summer_2026/SpeX_Summer_2026/combined/spex-sxd_cII-260_2017201002_2010A095_2046-2047comb.fits")
h = hdu[0].header
hdu.close()
print(h)

SIMPLE  =                    T / conforms to FITS standard                      BITPIX  =                  -64 / array data type                                NAXIS   =                    3 / number of array dimensions                     NAXIS1  =                 1014                                                  NAXIS2  =                    4                                                  NAXIS3  =                    6                                                  DIVISOR =                   32 / Normalization value                            ORIGIN  = 'Institute for Astronomy'                                             TELESCOP= 'NASA IRTF'                                                           OBSERVER= 'Your_Name'                                                           PROG_ID =                                                                       OBJECT  = 'cII-260 '                                                            NDR     =                   32 / Number of Non-Destructive Reads                SRT_AM  =                1.133 / Start airmass                                  AVE_AM  =                1.132 / Average airmass                                END_AM  =                1.131 / End airmass                                    SRT_HA  = '-00:27:13.35'       / Start hour angle (hours)                       AVE_HA  = '-00:26:01.56'       / Average hour angle (hours)                     END_HA  = '-00:24:49.77'       / End hour angle (hours)                         PA      =                  0.0 / Position Angle E of N (deg)                    RA      = '+05:40:19.96'       / Right Ascension                                DEC     = '-07:25:56.1'        / Declination                                    ITIME   =                120.0 / Integration time (sec)                         NCOADDS =                    1 / Number of COADDS                               IMGITIME=                120.0 / Image integration time, NCOADDSxITIME (sec)    TOTITIME=               1440.0 / Total integration time (sec)                   SRT_TIME= '05:44:48.979665'    / Start observations time in UTC                 AVE_TIME= '05:46:00.59'        / Average observation time in UTC                END_TIME= '05:47:12.197309'    / End observation time in UTC                    SRT_DATE= '2010-02-17'         / Start observations date in UTC                 AVE_DATE= '2010-02-17'         / Average observation date in UTC                END_DATE= '2010-02-17'         / End observation date in UTC                    SRT_MJD =    55244.23945578316 / Start Modified Julian Date                     AVE_MJD =    55244.24028458897 / Average Modified Julian Date                   END_MJD =    55244.24111339478 / End Modified Julian Date                       FILENAME= 'calspec2046-2047.fits' / File name                                   MODE    = 'ShortXD '           / Instrument Mode                                INSTR   = 'SpeX    '           / Instrument                                     MODULE  = 'telluric'           / Creation module                                VERSION = '1.2b4   '           / pySpextool version                             FLAT    = 'flat2027-2041.fits' / Flat field image                               WAVECAL = 'wavecal2027-2041.fits' / Wavecal file                                WCTYPE  = '1DXD    '           / Wavelength calibration type                    WAVETYPE= 'vacuum  '           / Wavelength type                                NORDERS =                    6 / Number of orders                               ORDERS  = '3,4,5,6,7,8'        / Orders                                         NAPS    =                    1 / Number of apertures                            PLTSCALE=                 0.15 / Plate scale (arcseconds pixel-1)               SLTH_ARC=                 15.0 / Nominal slit height (arcseconds)               SLTW_ARC=                  0.5 / Slit width (arcseconds)                        SLTH_PIX=                100.0 / Nominal slit height (pixels)                   SLTW_PIX=                  3.3 / Slit width (pixels)                            RP      =                 1200 / Average resolving power                        BDPXFIX =                    F / Bad pixels fixed?                              THRESH  =                    7 / Bad pixel sigma threshold                      OPTEXT  =                    T / Optimal extraction?                            SUMEXT  =                    F / Sum extraction?                                PSFRAD  =                  1.5 / PSF radius (arcseconds)                        APRADII =                                                                       XUNITS  = 'um      '           / Units of the x axis                            YUNITS  = 'W m-2 um-1'         / Units of the y axis                            LXUNITS = '$\mu$m  '           / LateX units of the x axis                      LYUNITS = '(W m$^{-2}$ $\mu$m$^{-1}$)' / LateX units of the y axis              LXLABEL = 'Wavelength ($\mu$m)' / LateX x-axis label                            LYLABEL = '$f_\lambda$(W m$^{-2}$ $\mu$m$^{-1}$)' / LateX y-axis flux label     LULABEL = '$\sigma$(W m$^{-2}$ $\mu$m$^{-1}$)' / LateX y-axis uncertainty label CMB_NFL =                    2 / Number of spectra files combined               CMB_NAP =                    0 / Number of apertures combined                   CMB_STAT= 'robust weighted mean' / Combination statistic                        CMB_THSH=                    8 / Combination robust threshold (if used)         TC_OFILE= 'combspec2046-2047.fits' / Telluric object input file                 TC_SFILE= 'combspec2042-2045.fits' / Telluric standard input file               TC_STDID= 'hd37887 '           / Telluric standard                              TC_STDST= 'B9.5IV/V'           / Telluric spectral type                         TC_STDT =                10700 / Telluric effective temperature (K)             TC_STDB =                 7.69 / Telluric standard B mag                        TC_STDV =                 7.67 / Telluric standard V mag                        TC_STDRV=                62.96 / Telluric standard radial velocity (km s-1)     TC_DAM  =                 0.02 / Telluric Average airmass difference            TC_DAN  =                 3.71 / Telluric angular separation (deg) of obj and stTC_TYPE = 'A0V     '           / Telluric correction type                       TC_METH = 'deconvolution'      / Kernel creation method                         TC_MXDEV=              0.00666 / Telluric maxmimum % deviation of Vega-data     TC_RMS  =              0.00321 / Telluric RMS deviation of Vega-data            TC_SO003= '-0.16   '           / Standard shift (pixels) for order 003          TC_SO004= '-0.15   '           / Standard shift (pixels) for order 004          TC_SO005= '-0.11   '           / Standard shift (pixels) for order 005          TC_SO006= '1.16    '           / Standard shift (pixels) for order 006          TC_SO007= '0.0     '           / Standard shift (pixels) for order 007          TC_SO008= '0.0     '           / Standard shift (pixels) for order 008          HISTORY Spextool FITS files contain an array of size                            HISTORY [nwaves,4,norders*naps]. The ith image (array[*,*,i]) contains          HISTORY the data for a single extraction aperture within an order such          HISTORY that, lambda=array[*,0,i], flux=array[*,1,i],                           HISTORY uncertainty=array[*,2,i],flag=array[*,3,i].  The zeroth image           HISTORY (array[*,*,0]) contains the data for the aperture in the order          HISTORY closest to the bottom of the detector that is closest to the            HISTORY bottom of the slit (i.e. also closest to the bottom of the              HISTORY detector).  Moving up the detector, the FITS array is filled in         HISTORY with subsequent extraction apertures.  If no orders have been           HISTORY deselected in the extraction process, the contents of the ith           HISTORY aperture in order j can be found as follows:                            HISTORY lambda=array[*,0,{j-min(orders)}*naps + (i-1)],                         HISTORY flux=array[*,1,{j-min(orders)}*naps + (i-1)],                           HISTORY uncertainty=array[*,2,{j-min(orders)}*naps + (i-1)],                    HISTORY flag=array[*,3,{j-min(orders)}*naps + (i-1)].                           HISTORY                                                                         HISTORY The spectra in the file(s) spectra2046.fits, spectra2047.fits           HISTORY were combined using a robust weighted mean with a sigma                 HISTORY threshold of 8.  Aperture 1 modifications: The scale factors            HISTORY were determined using order 5 and are: 0.8875773238319252,              HISTORY 1.1450325770565815.                                                     END

In [8]:
hdu = fits.open("/Users/epritchard/Research/CSL_Summer_2026/SpeX_Summer_2026/combined/spex-sxd_P-2010H2_20100422_2010A999_55-64.fits")
h = hdu[0].header
hdu.close()
print(h)

SIMPLE  =                    T / conforms to FITS standard                      BITPIX  =                  -64 / array data type                                NAXIS   =                    3 / number of array dimensions                     NAXIS1  =                 1014                                                  NAXIS2  =                    4                                                  NAXIS3  =                    6                                                  DIVISOR =                   32 / Normalization value                            ORIGIN  = 'Institute for Astronomy'                                             TELESCOP= 'NASA IRTF'                                                           OBSERVER= 'Your_Name'                                                           PROG_ID =                                                                       OBJECT  = 'P/2010H2'                                                            TABLE_MS=              512.452 / msec to clock out array                        GFLT    = 'H+K     '           / menu=12,pos=533333                             SLIT    = '0.8x15  '           / menu=4,pos=153000                              SRT_AM  =                1.086 / Start airmass                                  AVE_AM  =                1.107 / Average airmass                                END_AM  =                 1.13 / End airmass                                    SRT_HA  = '++01:11:08.48'      / Start hour angle (hours)                       AVE_HA  = '+01:23:46.18'       / Average hour angle (hours)                     END_HA  = '++01:35:48.98'      / End hour angle (hours)                         PA      =                45.72 / Position Angle E of N (deg)                    RA      = '+13:34:35.78'       / Right Ascension                                DEC     = '++04:47:55.6'       / Declination                                    ITIME   =                150.0 / Integration time (sec)                         NCOADDS =                    1 / Number of COADDS                               IMGITIME=                150.0 / Image integration time, NCOADDSxITIME (sec)    TOTITIME=               8640.0 / Total integration time (sec)                   SRT_TIME= '11:03:48.839566'    / Start observations time in UTC                 AVE_TIME= '11:16:30.52'        / Average observation time in UTC                END_TIME= '11:28:55.355730'    / End observation time in UTC                    SRT_DATE= '2010-04-22'         / Start observations date in UTC                 AVE_DATE= '2010-04-22'         / Average observation date in UTC                END_DATE= '2010-04-22'         / End observation date in UTC                    SRT_MJD =   55308.460981939425 / Start Modified Julian Date                     AVE_MJD =    55308.46979764316 / Average Modified Julian Date                   END_MJD =   55308.478418469094 / End Modified Julian Date                       FILENAME= 'calspec55-64.fits'  / File name                                      MODE    = 'ShortXD '           / Instrument Mode                                INSTR   = 'SpeX    '           / Instrument                                     USERCOM = '*Comet  '           / User comment                                   MODULE  = 'telluric'           / Creation module                                VERSION = '1.5b10  '           / pySpextool version                             AIMAGE  = 'spc0055.a.fits'     / A image                                        SKYORDRK= 'spc0056.b.fits'     / Sky or dark image                              FLAT    = 'flat65-71.fits'     / Flat field image                               FLFIELD =                    T / Flat fielded?                                  WAVECAL = 'wavecal65-71.fits'  / Wavecal file                                   WCTYPE  = '1DXD    '           / Wavelength calibration type                    WAVETYPE= 'vacuum  '           / Wavelength type                                NORDERS =                    6 / Number of orders                               ORDERS  = '3,4,5,6,7,8'        / Orders                                         NAPS    =                    1 / Number of apertures                            PLTSCALE=                 0.15 / Plate scale (arcseconds pixel-1)               SLTH_ARC=                 15.0 / Nominal slit height (arcseconds)               SLTW_ARC=                  0.8 / Slit width (arcseconds)                        SLTH_PIX=                100.0 / Nominal slit height (pixels)                   SLTW_PIX=                  5.3 / Slit width (pixels)                            RP      =                  750 / Average resolving power                        APOSO003= '3.4928,11.0258'     / Aperture positions (arcseconds) for order 003  ARADO003= '1.5,1.5 '           / Aperture radii (arcseconds) for order 003      APOSO004= '3.4764,11.0179'     / Aperture positions (arcseconds) for order 004  ARADO004= '1.5,1.5 '           / Aperture radii (arcseconds) for order 004      APOSO005= '3.463,10.9053'      / Aperture positions (arcseconds) for order 005  ARADO005= '1.5,1.5 '           / Aperture radii (arcseconds) for order 005      APOSO006= '3.4614,10.9612'     / Aperture positions (arcseconds) for order 006  ARADO006= '1.5,1.5 '           / Aperture radii (arcseconds) for order 006      APOSO007= '3.5195,10.9046'     / Aperture positions (arcseconds) for order 007  ARADO007= '1.5,1.5 '           / Aperture radii (arcseconds) for order 007      APOSO008= '3.4385,10.81'       / Aperture positions (arcseconds) for order 008  ARADO008= '1.5,1.5 '           / Aperture radii (arcseconds) for order 008      BGSUB   =                    T / Background subtraction?                        BGREGS  =  / Background regions (arcseconds)                                    BGSTART =                  2.5 / Background annulus start (arcseconds)          BGWIDTH =                  4.0 / Background annulus width (arcseconds)          BGFITDEG=                    0 / Background fit degree                          BDPXFIX =                    F / Bad pixels fixed?                              THRESH  =                    7 / Bad pixel sigma threshold                      OPTEXT  =                    T / Optimal extraction?                            SUMEXT  =                    F / Sum extraction?                                PSFRAD  =                  1.5 / PSF radius (arcseconds)                        SNRO003 = '839     '           /  Median S/N for order 003                      SNRO004 = '1203    '           /  Median S/N for order 004                      SNRO005 = '1201    '           /  Median S/N for order 005                      SNRO006 = '797     '           /  Median S/N for order 006                      SNRO007 = '503     '           /  Median S/N for order 007                      SNRO008 = '196     '           /  Median S/N for order 008                      XUNITS  = 'um      '           / Units of the x axis                            YUNITS  = 'DN s-1  '           / Units of the y axis                            LXUNITS = '$\mu$m  '           / LateX units of the x axis                      LYUNITS = '' / LateX units of the y axis                                        LXLABEL = 'Wavelength ($\mu$m)' / LateX x-axis label                            LYLABEL = 'Reflectance()'      / LateX y-axis flux label                        LULABEL = '$\sigma$()'         / LateX y-axis uncertainty label                 CMB_NFL =                   10 / Number of spectra files combined               CMB_NAP =                    0 / Number of apertures combined                   CMB_STAT= 'robust weighted mean' / Combination statistic                        CMB_THSH=                    8 / Combination robust threshold (if used)         TC_SFILE= 'combspec39-46.fits' / Telluric standard input file                   TC_STDID= 'HD127913'           / Telluric standard                              TC_STDST= 'G6V     '           / Telluric standard spectral type                TC_TYPE = 'reflectance'        / Telluric correction type                       TC_METH = 'deconvolution'      / Kernel creation method                         HISTORY Spextool FITS files contain an array of size                            HISTORY [nwaves,4,norders*naps]. The ith image (array[*,*,i]) contains          HISTORY the data for a single extraction aperture within an order such          HISTORY that, lambda=array[*,0,i], flux=array[*,1,i],                           HISTORY uncertainty=array[*,2,i],flag=array[*,3,i].  The zeroth image           HISTORY (array[*,*,0]) contains the data for the aperture in the order          HISTORY closest to the bottom of the detector that is closest to the            HISTORY bottom of the slit (i.e. also closest to the bottom of the              HISTORY detector).  Moving up the detector, the FITS array is filled in         HISTORY with subsequent extraction apertures.  If no orders have been           HISTORY deselected in the extraction process, the contents of the ith           HISTORY aperture in order j can be found as follows:                            HISTORY lambda=array[*,0,{j-min(orders)}*naps + (i-1)],                         HISTORY flux=array[*,1,{j-min(orders)}*naps + (i-1)],                           HISTORY uncertainty=array[*,2,{j-min(orders)}*naps + (i-1)],                    HISTORY flag=array[*,3,{j-min(orders)}*naps + (i-1)].                           HISTORY                                                                         HISTORY The spectra in the file(s) spectra0055.fits, spectra0056.fits,          HISTORY spectra0057.fits, spectra0058.fits, spectra0059.fits,                   HISTORY spectra0060.fits, spectra0061.fits, spectra0062.fits,                   HISTORY spectra0063.fits, spectra0064.fits were combined using a robust         HISTORY weighted mean with a sigma threshold of 8.  Aperture 1                  HISTORY modifications: The scale factors were determined using order 6          HISTORY and are: 1.0391577310025217, 1.256642619922299,                         HISTORY 1.0556982169850289, 0.9903082459585918, 0.9656244010905697,             HISTORY 0.8903671703084112, 0.9684723438239539, 1.009883327601864,              HISTORY 0.9662756175481918, 1.023907789169599.                                  END

# OKAY lets do more script making! 

Imma run off the assumption that the best indicator of moving versus fixed objects is the units of the y_axis (checking standards sometimes works but other times its iffy)

(ND/s --> reflectance? --> moving source)

(W m-2 um-1 --> energy flux --> fixed source)

In [9]:
# Some setup o7
COMBINED_DIR = Path("combined")

MOVING_PS_DF = pd.DataFrame()
FIXED_PS_DF = pd.DataFrame()

In [15]:
hdu = fits.open(f"{COMBINED_DIR}/spex-sxd_P-2010H2_20100422_2010A999_55-64.fits")
h = hdu[0].header
hdu.close()
h["YUNITS"]

'DN s-1'

In [13]:
help(h)

Help on Header in module astropy.io.fits.header object:

class Header(builtins.object)
 |  Header(cards=[], copy=False)
 |
 |  FITS header class.  This class exposes both a dict-like interface and a
 |  list-like interface to FITS headers.
 |
 |  The header may be indexed by keyword and, like a dict, the associated value
 |  will be returned.  When the header contains cards with duplicate keywords,
 |  only the value of the first card with the given keyword will be returned.
 |  It is also possible to use a 2-tuple as the index in the form (keyword,
 |  n)--this returns the n-th value with that keyword, in the case where there
 |  are duplicate keywords.
 |
 |  For example::
 |
 |      >>> header['NAXIS']
 |      0
 |      >>> header[('FOO', 1)]  # Return the value of the second FOO keyword
 |      'foo'
 |
 |  The header may also be indexed by card number::
 |
 |      >>> header[0]  # Return the value of the first card in the header
 |      'T'
 |
 |  Commentary keywords such as HISTORY and COMMENT are special cases: When
 |  indexing the Header object with either 'HISTORY' or 'COMMENT' a list of all
 |  the HISTORY/COMMENT values is returned::
 |
 |      >>> header['HISTORY']
 |      This is the first history entry in this header.
 |      This is the second history entry in this header.
 |      ...
 |
 |  See the Astropy documentation for more details on working with headers.
 |
 |  Notes
 |  -----
 |  Although FITS keywords must be exclusively upper case, retrieving an item
 |  in a `Header` object is case insensitive.
 |
 |  Methods defined here:
 |
 |  __add__(self, other)
 |
 |  __contains__(self, keyword)
 |
 |  __copy__(self)
 |
 |  __deepcopy__(self, *args, **kwargs)
 |
 |  __delitem__(self, key)
 |
 |  __eq__(self, other)
 |      Two Headers are equal only if they have the exact same string
 |      representation.
 |
 |  __getitem__(self, key)
 |
 |  __iadd__(self, other)
 |
 |  __init__(self, cards=[], copy=False)
 |      Construct a `Header` from an iterable and/or text file.
 |
 |      Parameters
 |      ----------
 |      cards : list of `Card`, optional
 |          The cards to initialize the header with. Also allowed are other
 |          `Header` (or `dict`-like) objects.
 |
 |          .. versionchanged:: 1.2
 |              Allowed ``cards`` to be a `dict`-like object.
 |
 |      copy : bool, optional
 |
 |          If ``True`` copies the ``cards`` if they were another `Header`
 |          instance.
 |          Default is ``False``.
 |
 |          .. versionadded:: 1.3
 |
 |  __iter__(self)
 |
 |  __len__(self)
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  __setitem__(self, key, value)
 |
 |  __str__(self)
 |      Return str(self).
 |
 |  add_blank(self, value='', before=None, after=None)
 |      Add a blank card.
 |
 |      Parameters
 |      ----------
 |      value : str, optional
 |          Text to be added.
 |
 |      before : str or int, optional
 |          Same as in `Header.update`
 |
 |      after : str or int, optional
 |          Same as in `Header.update`
 |
 |  add_comment(self, value, before=None, after=None)
 |      Add a ``COMMENT`` card.
 |
 |      Parameters
 |      ----------
 |      value : str
 |          Text to be added.
 |
 |      before : str or int, optional
 |          Same as in `Header.update`
 |
 |      after : str or int, optional
 |          Same as in `Header.update`
 |
 |  add_history(self, value, before=None, after=None)
 |      Add a ``HISTORY`` card.
 |
 |      Parameters
 |      ----------
 |      value : str
 |          History text to be added.
 |
 |      before : str or int, optional
 |          Same as in `Header.update`
 |
 |      after : str or int, optional
 |          Same as in `Header.update`
 |
 |  append(self, card=None, useblanks=True, bottom=False, end=False)
 |      Appends a new keyword+value card to the end of the Header, similar
 |      to `list.append`.
 |
 |      By default if the last cards in the Header have commentary keywords,
 |      this will append the new keyword before the commentary (unless the new
 |      keyword is also commentary).
 |
 |      Also differs from `list.append` in that it can be called with no
 |      arguments: In this case a blank card is appended to the end of the
 |      Header.  In the case all the keyword arguments are ignored.
 |
 |      Parameters
 |      ----------
 |      card : str, tuple
 |          A keyword or a (keyword, value, [comment]) tuple representing a
 |          single header card; the comment is optional in which case a
 |          2-tuple may be used
 |
 |      useblanks : bool, optional
 |          If there are blank cards at the end of the Header, replace the
 |          first blank card so that the total number of cards in the Header
 |          does not increase.  Otherwise preserve the number of blank cards.
 |
 |      bottom : bool, optional
 |          If True, instead of appending after the last non-commentary card,
 |          append after the last non-blank card.
 |
 |      end : bool, optional
 |          If True, ignore the useblanks and bottom options, and append at the
 |          very end of the Header.
 |
 |  clear(self)
 |      Remove all cards from the header.
 |
 |  copy(self, strip=False)
 |      Make a copy of the :class:`Header`.
 |
 |      .. versionchanged:: 1.3
 |          `copy.copy` and `copy.deepcopy` on a `Header` will call this
 |          method.
 |
 |      Parameters
 |      ----------
 |      strip : bool, optional
 |          If `True`, strip any headers that are specific to one of the
 |          standard HDU types, so that this header can be used in a different
 |          HDU.
 |
 |      Returns
 |      -------
 |      `Header`
 |          A new :class:`Header` instance.
 |
 |  count(self, keyword)
 |      Returns the count of the given keyword in the header, similar to
 |      `list.count` if the Header object is treated as a list of keywords.
 |
 |      Parameters
 |      ----------
 |      keyword : str
 |          The keyword to count instances of in the header
 |
 |  extend(
 |      self,
 |      cards,
 |      strip=True,
 |      unique=False,
 |      update=False,
 |      update_first=False,
 |      useblanks=True,
 |      bottom=False,
 |      end=False
 |  )
 |      Appends multiple keyword+value cards to the end of the header, similar
 |      to `list.extend`.
 |
 |      Parameters
 |      ----------
 |      cards : iterable
 |          An iterable of (keyword, value, [comment]) tuples; see
 |          `Header.append`.
 |
 |      strip : bool, optional
 |          Remove any keywords that have meaning only to specific types of
 |          HDUs, so that only more general keywords are added from extension
 |          Header or Card list (default: `True`).
 |
 |      unique : bool, optional
 |          If `True`, ensures that no duplicate keywords are appended;
 |          keywords already in this header are simply discarded.  The
 |          exception is commentary keywords (COMMENT, HISTORY, etc.): they are
 |          only treated as duplicates if their values match.
 |
 |      update : bool, optional
 |          If `True`, update the current header with the values and comments
 |          from duplicate keywords in the input header.  This supersedes the
 |          ``unique`` argument.  Commentary keywords are treated the same as
 |          if ``unique=True``.
 |
 |      update_first : bool, optional
 |          If the first keyword in the header is 'SIMPLE', and the first
 |          keyword in the input header is 'XTENSION', the 'SIMPLE' keyword is
 |          replaced by the 'XTENSION' keyword.  Likewise if the first keyword
 |          in the header is 'XTENSION' and the first keyword in the input
 |          header is 'SIMPLE', the 'XTENSION' keyword is replaced by the
 |          'SIMPLE' keyword.  This behavior is otherwise dumb as to whether or
 |          not the resulting header is a valid primary or extension header.
 |          This is mostly provided to support backwards compatibility with the
 |          old ``Header.fromTxtFile`` method, and only applies if
 |          ``update=True``.
 |
 |      useblanks, bottom, end : bool, optional
 |          These arguments are passed to :meth:`Header.append` while appending
 |          new cards to the header.
 |
 |  get(self, key, default=None)
 |      Similar to :meth:`dict.get`--returns the value associated with keyword
 |      in the header, or a default value if the keyword is not found.
 |
 |      Parameters
 |      ----------
 |      key : str
 |          A keyword that may or may not be in the header.
 |
 |      default : optional
 |          A default value to return if the keyword is not found in the
 |          header.
 |
 |      Returns
 |      -------
 |      value: str, number, complex, bool, or ``astropy.io.fits.card.Undefined``
 |          The value associated with the given keyword, or the default value
 |          if the keyword is not in the header.
 |
 |  index(self, keyword, start=None, stop=None)
 |      Returns the index if the first instance of the given keyword in the
 |      header, similar to `list.index` if the Header object is treated as a
 |      list of keywords.
 |
 |      Parameters
 |      ----------
 |      keyword : str
 |          The keyword to look up in the list of all keywords in the header
 |
 |      start : int, optional
 |          The lower bound for the index
 |
 |      stop : int, optional
 |          The upper bound for the index
 |
 |  insert(self, key, card, useblanks=True, after=False)
 |      Inserts a new keyword+value card into the Header at a given location,
 |      similar to `list.insert`.
 |
 |      New keywords can also be inserted relative to existing keywords
 |      using, for example::
 |
 |          >>> header = Header({"NAXIS1": 10})
 |          >>> header.insert('NAXIS1', ('NAXIS', 2, 'Number of axes'))
 |
 |      to insert before an existing keyword, or::
 |
 |          >>> header.insert('NAXIS1', ('NAXIS2', 4096), after=True)
 |
 |      to insert after an existing keyword.
 |
 |      Parameters
 |      ----------
 |      key : int, str, or tuple
 |          The index into the list of header keywords before which the
 |          new keyword should be inserted, or the name of a keyword before
 |          which the new keyword should be inserted.  Can also accept a
 |          (keyword, index) tuple for inserting around duplicate keywords.
 |
 |      card : str, tuple
 |          A keyword or a (keyword, value, [comment]) tuple; see
 |          `Header.append`
 |
 |      useblanks : bool, optional
 |          If there are blank cards at the end of the Header, replace the
 |          first blank card so that the total number of cards in the Header
 |          does not increase.  Otherwise preserve the number of blank cards.
 |
 |      after : bool, optional
 |          If set to `True`, insert *after* the specified index or keyword,
 |          rather than before it.  Defaults to `False`.
 |
 |  items(self)
 |      Like :meth:`dict.items`.
 |
 |  keys(self)
 |      Like :meth:`dict.keys`--iterating directly over the `Header`
 |      instance has the same behavior.
 |
 |  pop(self, *args)
 |      Works like :meth:`list.pop` if no arguments or an index argument are
 |      supplied; otherwise works like :meth:`dict.pop`.
 |
 |  popitem(self)
 |      Similar to :meth:`dict.popitem`.
 |
 |  remove(self, keyword, ignore_missing=False, remove_all=False)
 |      Removes the first instance of the given keyword from the header similar
 |      to `list.remove` if the Header object is treated as a list of keywords.
 |
 |      Parameters
 |      ----------
 |      keyword : str
 |          The keyword of which to remove the first instance in the header.
 |
 |      ignore_missing : bool, optional
 |          When True, ignores missing keywords.  Otherwise, if the keyword
 |          is not present in the header a KeyError is raised.
 |
 |      remove_all : bool, optional
 |          When True, all instances of keyword will be removed.
 |          Otherwise only the first instance of the given keyword is removed.
 |
 |  rename_keyword(self, oldkeyword, newkeyword, force=False)
 |      Rename a card's keyword in the header.
 |
 |      Parameters
 |      ----------
 |      oldkeyword : str or int
 |          Old keyword or card index
 |
 |      newkeyword : str
 |          New keyword
 |
 |      force : bool, optional
 |          When `True`, if the new keyword already exists in the header, force
 |          the creation of a duplicate keyword. Otherwise a
 |          `ValueError` is raised.
 |
 |  set(self, keyword, value=None, comment=None, before=None, after=None)
 |      Set the value and/or comment and/or position of a specified keyword.
 |
 |      If the keyword does not already exist in the header, a new keyword is
 |      created in the specified position, or appended to the end of the header
 |      if no position is specified.
 |
 |      This method is similar to :meth:`Header.update` prior to Astropy v0.1.
 |
 |      .. note::
 |          It should be noted that ``header.set(keyword, value)`` and
 |          ``header.set(keyword, value, comment)`` are equivalent to
 |          ``header[keyword] = value`` and
 |          ``header[keyword] = (value, comment)`` respectively.
 |
 |      Parameters
 |      ----------
 |      keyword : str
 |          A header keyword
 |
 |      value : str, optional
 |          The value to set for the given keyword; if None the existing value
 |          is kept, but '' may be used to set a blank value
 |
 |      comment : str, optional
 |          The comment to set for the given keyword; if None the existing
 |          comment is kept, but ``''`` may be used to set a blank comment
 |
 |      before : str, int, optional
 |          Name of the keyword, or index of the `Card` before which this card
 |          should be located in the header.  The argument ``before`` takes
 |          precedence over ``after`` if both specified.
 |
 |      after : str, int, optional
 |          Name of the keyword, or index of the `Card` after which this card
 |          should be located in the header.
 |
 |  setdefault(self, key, default=None)
 |      Similar to :meth:`dict.setdefault`.
 |
 |  strip(self)
 |      Strip cards specific to a certain kind of header.
 |
 |      Strip cards like ``SIMPLE``, ``BITPIX``, etc. so the rest of
 |      the header can be used to reconstruct another kind of header.
 |
 |  tofile(self, fileobj, sep='', endcard=True, padding=True, overwrite=False)
 |      Writes the header to file or file-like object.
 |
 |      By default this writes the header exactly as it would be written to a
 |      FITS file, with the END card included and padding to the next multiple
 |      of 2880 bytes.  However, aspects of this may be controlled.
 |
 |      Parameters
 |      ----------
 |      fileobj : path-like or file-like, optional
 |          Either the pathname of a file, or an open file handle or file-like
 |          object.
 |
 |      sep : str, optional
 |          The character or string with which to separate cards.  By default
 |          there is no separator, but one could use ``'\\n'``, for example, to
 |          separate each card with a new line
 |
 |      endcard : bool, optional
 |          If `True` (default) adds the END card to the end of the header
 |          string
 |
 |      padding : bool, optional
 |          If `True` (default) pads the string with spaces out to the next
 |          multiple of 2880 characters
 |
 |      overwrite : bool, optional
 |          If ``True``, overwrite the output file if it exists. Raises an
 |          ``OSError`` if ``False`` and the output file exists. Default is
 |          ``False``.
 |
 |  tostring(self, sep='', endcard=True, padding=True)
 |      Returns a string representation of the header.
 |
 |      By default this uses no separator between cards, adds the END card, and
 |      pads the string with spaces to the next multiple of 2880 bytes.  That
 |      is, it returns the header exactly as it would appear in a FITS file.
 |
 |      Parameters
 |      ----------
 |      sep : str, optional
 |          The character or string with which to separate cards.  By default
 |          there is no separator, but one could use ``'\\n'``, for example, to
 |          separate each card with a new line
 |
 |      endcard : bool, optional
 |          If True (default) adds the END card to the end of the header
 |          string
 |
 |      padding : bool, optional
 |          If True (default) pads the string with spaces out to the next
 |          multiple of 2880 characters
 |
 |      Returns
 |      -------
 |      str
 |          A string representing a FITS header.
 |
 |  totextfile(self, fileobj, endcard=False, overwrite=False)
 |      Write the header as text to a file or a file-like object.
 |
 |      Equivalent to::
 |
 |          >>> Header.tofile(fileobj, sep='\n', endcard=False,
 |          ...               padding=False, overwrite=overwrite)
 |
 |      See Also
 |      --------
 |      tofile
 |
 |  update(self, *args, **kwargs)
 |      Update the Header with new keyword values, updating the values of
 |      existing keywords and appending new keywords otherwise; similar to
 |      `dict.update`.
 |
 |      `update` accepts either a dict-like object or an iterable.  In the
 |      former case the keys must be header keywords and the values may be
 |      either scalar values or (value, comment) tuples.  In the case of an
 |      iterable the items must be (keyword, value) tuples or (keyword, value,
 |      comment) tuples.
 |
 |      Arbitrary arguments are also accepted, in which case the update() is
 |      called again with the kwargs dict as its only argument.  That is,
 |
 |      ::
 |
 |          >>> header.update(NAXIS1=100, NAXIS2=100)
 |
 |      is equivalent to::
 |
 |          header.update({'NAXIS1': 100, 'NAXIS2': 100})
 |
 |  values(self)
 |      Like :meth:`dict.values`.
 |
 |  ----------------------------------------------------------------------
 |  Class methods defined here:
 |
 |  fromfile(fileobj, sep='', endcard=True, padding=True)
 |      Similar to :meth:`Header.fromstring`, but reads the header string from
 |      a given file-like object or filename.
 |
 |      Parameters
 |      ----------
 |      fileobj : str, file-like
 |          A filename or an open file-like object from which a FITS header is
 |          to be read.  For open file handles the file pointer must be at the
 |          beginning of the header.
 |
 |      sep : str, optional
 |          The string separating cards from each other, such as a newline.  By
 |          default there is no card separator (as is the case in a raw FITS
 |          file).
 |
 |      endcard : bool, optional
 |          If True (the default) the header must end with an END card in order
 |          to be considered valid.  If an END card is not found an
 |          `OSError` is raised.
 |
 |      padding : bool, optional
 |          If True (the default) the header will be required to be padded out
 |          to a multiple of 2880, the FITS header block size.  Otherwise any
 |          padding, or lack thereof, is ignored.
 |
 |      Returns
 |      -------
 |      `Header`
 |          A new `Header` instance.
 |
 |  fromkeys(iterable, value=None)
 |      Similar to :meth:`dict.fromkeys`--creates a new `Header` from an
 |      iterable of keywords and an optional default value.
 |
 |      This method is not likely to be particularly useful for creating real
 |      world FITS headers, but it is useful for testing.
 |
 |      Parameters
 |      ----------
 |      iterable
 |          Any iterable that returns strings representing FITS keywords.
 |
 |      value : optional
 |          A default value to assign to each keyword; must be a valid type for
 |          FITS keywords.
 |
 |      Returns
 |      -------
 |      `Header`

In [14]:
h

SIMPLE  =                    T / conforms to FITS standard
BITPIX  =                  -64 / array data type
NAXIS   =                    3 / number of array dimensions
NAXIS1  =                 1014
NAXIS2  =                    4
NAXIS3  =                    6
DIVISOR =                   32 / Normalization value
ORIGIN  = 'Institute for Astronomy'
TELESCOP= 'NASA IRTF'
OBSERVER= 'Your_Name'
PROG_ID =
OBJECT  = 'P/2010H2'
TABLE_MS=              512.452 / msec to clock out array
GFLT    = 'H+K     '           / menu=12,pos=533333
SLIT    = '0.8x15  '           / menu=4,pos=153000
SRT_AM  =                1.086 / Start airmass
AVE_AM  =                1.107 / Average airmass
END_AM  =                 1.13 / End airmass
SRT_HA  = '++01:11:08.48'      / Start hour angle (hours)
AVE_HA  = '+01:23:46.18'       / Average hour angle (hours)
END_HA  = '++01:35:48.98'      / End hour angle (hours)
PA      =                45.72 / Position Angle E of N (deg)
RA      = '+13:34:35.78'       / Right Ascension
DEC     = '++04:47:55.6'       / Declination
ITIME   =                150.0 / Integration time (sec)
NCOADDS =                    1 / Number of COADDS
IMGITIME=                150.0 / Image integration time, NCOADDSxITIME (sec)
TOTITIME=               8640.0 / Total integration time (sec)
SRT_TIME= '11:03:48.839566'    / Start observations time in UTC
AVE_TIME= '11:16:30.52'        / Average observation time in UTC
END_TIME= '11:28:55.355730'    / End observation time in UTC
SRT_DATE= '2010-04-22'         / Start observations date in UTC
AVE_DATE= '2010-04-22'         / Average observation date in UTC
END_DATE= '2010-04-22'         / End observation date in UTC
SRT_MJD =   55308.460981939425 / Start Modified Julian Date
AVE_MJD =    55308.46979764316 / Average Modified Julian Date
END_MJD =   55308.478418469094 / End Modified Julian Date
FILENAME= 'calspec55-64.fits'  / File name
MODE    = 'ShortXD '           / Instrument Mode
INSTR   = 'SpeX    '           / Instrument
USERCOM = '*Comet  '           / User comment
MODULE  = 'telluric'           / Creation module
VERSION = '1.5b10  '           / pySpextool version
AIMAGE  = 'spc0055.a.fits'     / A image
SKYORDRK= 'spc0056.b.fits'     / Sky or dark image
FLAT    = 'flat65-71.fits'     / Flat field image
FLFIELD =                    T / Flat fielded?
WAVECAL = 'wavecal65-71.fits'  / Wavecal file
WCTYPE  = '1DXD    '           / Wavelength calibration type
WAVETYPE= 'vacuum  '           / Wavelength type
NORDERS =                    6 / Number of orders
ORDERS  = '3,4,5,6,7,8'        / Orders
NAPS    =                    1 / Number of apertures
PLTSCALE=                 0.15 / Plate scale (arcseconds pixel-1)
SLTH_ARC=                 15.0 / Nominal slit height (arcseconds)
SLTW_ARC=                  0.8 / Slit width (arcseconds)
SLTH_PIX=                100.0 / Nominal slit height (pixels)
SLTW_PIX=                  5.3 / Slit width (pixels)
RP      =                  750 / Average resolving power
APOSO003= '3.4928,11.0258'     / Aperture positions (arcseconds) for order 003
ARADO003= '1.5,1.5 '           / Aperture radii (arcseconds) for order 003
APOSO004= '3.4764,11.0179'     / Aperture positions (arcseconds) for order 004
ARADO004= '1.5,1.5 '           / Aperture radii (arcseconds) for order 004
APOSO005= '3.463,10.9053'      / Aperture positions (arcseconds) for order 005
ARADO005= '1.5,1.5 '           / Aperture radii (arcseconds) for order 005
APOSO006= '3.4614,10.9612'     / Aperture positions (arcseconds) for order 006
ARADO006= '1.5,1.5 '           / Aperture radii (arcseconds) for order 006
APOSO007= '3.5195,10.9046'     / Aperture positions (arcseconds) for order 007
ARADO007= '1.5,1.5 '           / Aperture radii (arcseconds) for order 007
APOSO008= '3.4385,10.81'       / Aperture positions (arcseconds) for order 008
ARADO008= '1.5,1.5 '           / Aperture radii (arcseconds) for order 008
BGSUB   =                    T / Background subtraction?
BGREGS  =  / Background regions (arcseconds)
BGSTART =                  2.5 / Background annulus start (arcseconds)
BGWIDTH =                  4.0 / Background annulus width (arcseconds)
BGFITDEG=                    0 / Background fit degree
BDPXFIX =                    F / Bad pixels fixed?
THRESH  =                    7 / Bad pixel sigma threshold
OPTEXT  =                    T / Optimal extraction?
SUMEXT  =                    F / Sum extraction?
PSFRAD  =                  1.5 / PSF radius (arcseconds)
SNRO003 = '839     '           /  Median S/N for order 003
SNRO004 = '1203    '           /  Median S/N for order 004
SNRO005 = '1201    '           /  Median S/N for order 005
SNRO006 = '797     '           /  Median S/N for order 006
SNRO007 = '503     '           /  Median S/N for order 007
SNRO008 = '196     '           /  Median S/N for order 008
XUNITS  = 'um      '           / Units of the x axis
YUNITS  = 'DN s-1  '           / Units of the y axis
LXUNITS = '$\mu$m  '           / LateX units of the x axis
LYUNITS = '' / LateX units of the y axis
LXLABEL = 'Wavelength ($\mu$m)' / LateX x-axis label
LYLABEL = 'Reflectance()'      / LateX y-axis flux label
LULABEL = '$\sigma$()'         / LateX y-axis uncertainty label
CMB_NFL =                   10 / Number of spectra files combined
CMB_NAP =                    0 / Number of apertures combined
CMB_STAT= 'robust weighted mean' / Combination statistic
CMB_THSH=                    8 / Combination robust threshold (if used)
TC_SFILE= 'combspec39-46.fits' / Telluric standard input file
TC_STDID= 'HD127913'           / Telluric standard
TC_STDST= 'G6V     '           / Telluric standard spectral type
TC_TYPE = 'reflectance'        / Telluric correction type
TC_METH = 'deconvolution'      / Kernel creation method
HISTORY Spextool FITS files contain an array of size
HISTORY [nwaves,4,norders*naps]. The ith image (array[*,*,i]) contains
HISTORY the data for a single extraction aperture within an order such
HISTORY that, lambda=array[*,0,i], flux=array[*,1,i],
HISTORY uncertainty=array[*,2,i],flag=array[*,3,i].  The zeroth image
HISTORY (array[*,*,0]) contains the data for the aperture in the order
HISTORY closest to the bottom of the detector that is closest to the
HISTORY bottom of the slit (i.e. also closest to the bottom of the
HISTORY detector).  Moving up the detector, the FITS array is filled in
HISTORY with subsequent extraction apertures.  If no orders have been
HISTORY deselected in the extraction process, the contents of the ith
HISTORY aperture in order j can be found as follows:
HISTORY lambda=array[*,0,{j-min(orders)}*naps + (i-1)],
HISTORY flux=array[*,1,{j-min(orders)}*naps + (i-1)],
HISTORY uncertainty=array[*,2,{j-min(orders)}*naps + (i-1)],
HISTORY flag=array[*,3,{j-min(orders)}*naps + (i-1)].
HISTORY
HISTORY The spectra in the file(s) spectra0055.fits, spectra0056.fits,
HISTORY spectra0057.fits, spectra0058.fits, spectra0059.fits,
HISTORY spectra0060.fits, spectra0061.fits, spectra0062.fits,
HISTORY spectra0063.fits, spectra0064.fits were combined using a robust
HISTORY weighted mean with a sigma threshold of 8.  Aperture 1
HISTORY modifications: The scale factors were determined using order 6
HISTORY and are: 1.0391577310025217, 1.256642619922299,
HISTORY 1.0556982169850289, 0.9903082459585918, 0.9656244010905697,
HISTORY 0.8903671703084112, 0.9684723438239539, 1.009883327601864,
HISTORY 0.9662756175481918, 1.023907789169599.

In [34]:
MASTER_DF = pd.DataFrame()

# Helpful Identifiers from .fits:
h["OBSERVER"]
h["OBJECT"]
h["RA"] 
h["DEC"]
# for asteroids:
h["SRT_MJD"]
h["END_MJD"]


# Important info from .fits
h["MODE"]
h["SRT_AM"]
h["END_AM"]
h["SRT_TIME"]
h["END_DATE"]
h["ORDERS"]

# Moving versus fixed:
h["YUNITS"]
h["TC_STDID"]
h["TC_STDST"]


# First lets loop thru all the availible files in the drive so far!
for file in COMBINED_DIR.iterdir():

    _info_dict = {
        "OBSERVER": None,
        "OBJECT" : None,
        "RA" : None,
        "DEC" : None,
        "SRT_MJD"  : None,
        "END_MJD" : None,
        "MODE" : None,
        "SRT_AM" : None,
        "END_AM" : None,
        "SRT_TIME" : None,
        "END_DATE" : None,
        "ORDER" : None,
        "YUNITS" : None,
        "TC_STDID" : None,
        "TC_STDST" : None
        }

    # For each object we will read in their header and immediately close the file to minimize RAM usage
    hdu = fits.open(f"{file}")
    h = hdu[0].header
    hdu.close()

    # To start, we will distinguish between fixed and moving sources then grab some important info about the data reduction / spectra availible.
    # The main indicator I am using for fixed vs moving objects is the units of the observation: either flux density or reflectance
    # Flux density --> star or galaxy --> fixed object
    # Reflectance --> asteroid --> moving object
    # Will also use tc_type (Telluric correction type) as it also gives reflectance or A0V

    for key in _info_dict.keys():

        try:
            _info_dict[key] = h[key]
        except:
            print(f"Something went wrong with {key} in {file}")

    if h["YUNITS"] == "W m-2 um-1":
        _info_dict["OBJECT_TYPE"] = "Fixed"
        # _info_dict["YUNITS"] = h["YUNITS"]

    elif h["YUNITS"] == "DN s-1" or h["YUNITS"] == "reflectance":
        _info_dict["OBJECT_TYPE"] = "Moving"
        # _info_dict["YUNITS"] = h["YUNITS"]

    # print(_info_dict)

    MASTER_DF = pd.concat((MASTER_DF, pd.DataFrame(_info_dict, index=[0])), ignore_index=True)


    
    # if h["YUNITS"] not in units_list:
    #     units_list.append(h["YUNITS"])
    # if h["TC_TYPE"] not in tc_type:
    #     tc_type.append(h["TC_TYPE"])

MASTER_DF

Something went wrong with ORDER in combined/spex-sxd_phi-Per_20090110_2008B083_1-16comb.fits
Something went wrong with ORDER in combined/spex-prism_J0850+10_20061118_2006B072_233-238comb.fits
Something went wrong with ORDER in combined/spex-prism_J1254+4346_20100717_2010A999_1-10comb.fits
Something went wrong with ORDER in combined/spex-sxd_delta-Sco_20090110_2008B083_529-552comb.fits
Something went wrong with ORDER in combined/spex-sxd_V838-Mon_20090110_2008B083_261-276comb.fits
Something went wrong with ORDER in combined/spex-prism_Tmove3-id150431_20100715_2010A999_128-133comb.fits
Something went wrong with ORDER in combined/spex-sxd_phi-Per_20091122_2009B047_209-224comb.fits
Something went wrong with ORDER in combined/spex-prism_0116-1357_20091108_2009B009_83-88comb.fits
Something went wrong with ORDER in combined/spex-sxd_HD283572_2006201001_2009B086_30-66comb.fits
Something went wrong with ORDER in combined/spex-sxd_IRAS-16240-2430-W_20090414_nan_1-4.fits
Something went wrong with ORDER in combined/spex-sxd_Iapetus_2031201001_2009B077_33-45comb.fits
Something went wrong with ORDER in combined/spex-sxd_J2119+3039_20100717_2010A999_367-372comb.fits
Something went wrong with ORDER in combined/spex-prism_2M-1422+28_2030201001_2009B069_314-321comb.fits
Something went wrong with ORDER in combined/spex-sxd_IRAS-05256+3049_2014201001_2009B079_161-164comb.fits
Something went wrong with ORDER in combined/spex-sxd_cII-123_2018201002_2010A095_3050-3055comb.fits
Something went wrong with ORDER in combined/spex-prism_J0413+2440_20101224_2010B015_20-25.fits
Something went wrong with ORDER in combined/spex-prism_J2142-3101_20100707_2010A999_265-272comb.fits
Something went wrong with ORDER in combined/spex-sxd_cII-271_2018201002_2010A095_3118-3119comb.fits
Something went wrong with ORDER in combined/spex-sxd_48-Per_20090110_2008B083_109-128comb.fits
Something went wrong with ORDER in combined/spex-prism_taurus13-J041812+281938_20061118_2006B072_155-160comb.fits
Something went wrong with ORDER in combined/spex-prism_2000DN8_20100201_2009B074_5-38comb.fits
Something went wrong with ORDER in combined/spex-sxd_Titan_20100117_2009B067_7-12.fits
Something went wrong with ORDER in combined/spex-prism_121-grinan02_20100815_2010B080_52-59comb.fits
Something went wrong with ORDER in combined/spex-sxd_J0423+2453_20101224_2010B015_116-121.fits
Something went wrong with ORDER in combined/spex-prism_AUR-101_2012201011_2010B106_29-38comb.fits
Something went wrong with ORDER in combined/spex-sxd_bPic-216303_20101112_2010B999_80-105comb.fits
Something went wrong with ORDER in combined/spex-prism_Chaplin_2013201011_2010B071_125-144comb.fits
Something went wrong with ORDER in combined/spex-prism_5404-Uemura_20090914_2009B105_161-172.fits
Something went wrong with ORDER in combined/spex-sxd_28-Cyg_20091122_2009B047_57-68comb.fits
Something went wrong with ORDER in combined/spex-prism_J1401-2345_20110331_nan_198-209comb.fits
Something went wrong with ORDER in combined/spex-sxd_Titan_20090428_nan_1293-1298.fits
Something went wrong with ORDER in combined/spex-prism_SIPS-J1142-3904A_20100126_2009B036_75-80.fits
Something went wrong with ORDER in combined/spex-prism_WISE-0656+4205_20101218_2010B095_107-110.fits
Something went wrong with ORDER in combined/spex-prism_IC348-034214+315735_20090927_2009B039_130-139.fits
Something went wrong with ORDER in combined/spex-prism_HD-145127_20090404_2009A050_132-135.fits
Something went wrong with ORDER in combined/spex-sxd_cII-279_2017201002_2010A095_2095-2102comb.fits
Something went wrong with ORDER in combined/spex-prism_taurus22-J043212+243012_20061118_2006B072_104-109comb.fits
Something went wrong with ORDER in combined/spex-prism_IC348-034211+315700_20090928_2009B039_49-58.fits
Something went wrong with ORDER in combined/spex-sxd_Titan_20090106_2008B006_7-12.fits
Something went wrong with ORDER in combined/spex-prism_1644-Rafita_20100613_2010A002_58-83.fits
Something went wrong with ORDER in combined/spex-prism_49985_20091109_2009B028_153-198comb.fits
Something went wrong with ORDER in combined/spex-longxd2.3_epsAur_20110330_nan_122-135comb.fits
Something went wrong with ORDER in combined/spex-prism_TWA-30B_20100125_2009B036_99-114.fits
Something went wrong with ORDER in combined/spex-prism_137032-1998-UO1_2015201010_2010B046_11-30comb.fits
Something went wrong with ORDER in combined/spex-sxd_cII-237_2017201002_2010A095_2075-2078comb.fits
Something went wrong with ORDER in combined/spex-prism_2M-0337-35_2030201001_2009B069_51-60comb.fits
Something went wrong with ORDER in combined/spex-longxd2.3_LickCa4_20100228_2010A024_166-292comb.fits
Something went wrong with ORDER in combined/spex-prism_Roque25_20090930_2009B039_50-109comb.fits
Something went wrong with ORDER in combined/spex-sxd_beta-Lyr_20091122_2009B047_1-12comb.fits
Something went wrong with ORDER in combined/spex-sxd_HD-93521_20090110_2008B083_401-420comb.fits
Something went wrong with ORDER in combined/spex-prism_J1618-1321_20100707_2010A999_133-138comb.fits
Something went wrong with ORDER in combined/spex-sxd_Titan_20090722_nan_244-249.fits
Something went wrong with ORDER in combined/spex-prism_2MASS-103258-8-374221_20100126_2009B036_57-62.fits
Something went wrong with ORDER in combined/spex-prism_J2035-3110_20100707_2010A999_245-250comb.fits
Something went wrong with ORDER in combined/spex-sxd_25-Ori_20090110_2008B083_181-204comb.fits
Something went wrong with ORDER in combined/spex-prism_2006-SV19_20090808_2009B055_2075-2090.fits
Something went wrong with ORDER in combined/spex-prism_Teide-2_20091031_2009B033_407-418comb.fits
Something went wrong with ORDER in combined/spex-prism_10016_20091109_2009B028_223-242comb.fits
Something went wrong with ORDER in combined/spex-prism_J1816+2503_20100717_2010A999_160-167comb.fits
Something went wrong with ORDER in combined/spex-sxd_zeta-Tau_20091122_2009B047_349-368comb.fits
Something went wrong with ORDER in combined/spex-longxd1.9_Wild-2_20100216_2010A100_17-423.fits
Something went wrong with ORDER in combined/spex-sxd_Titan_20100614_2010A002_1-6.fits
Something went wrong with ORDER in combined/spex-prism_65679-1989-UQ_2015201010_2010B046_87-110comb.fits
Something went wrong with ORDER in combined/spex-sxd_MHOBD3_20100910_2010B999_25-70.fits
Something went wrong with ORDER in combined/spex-longxd1.9_Pers-cl3-cp1_20100204_2010A107_421-450.fits
Something went wrong with ORDER in combined/spex-prism_AUR-BD04_2010201011_2010B106_165-178comb.fits
Something went wrong with ORDER in combined/spex-prism_1749-Telamon_20090928_2009B053_107-120.fits
Something went wrong with ORDER in combined/spex-prism_CFHT-PL1_2030201001_2009B069_67-76comb.fits
Something went wrong with ORDER in combined/spex-prism_Mathilde_2013201011_2010B071_109-116comb.fits
Something went wrong with ORDER in combined/spex-sxd_IRAS-03220+3035-N_2014201001_2009B079_3-8comb.fits
Something went wrong with ORDER in combined/spex-sxd_CII-185_2016201002_2010A095_1009-1010comb.fits
Something went wrong with ORDER in combined/spex-prism_369-Aeria_20090612_2009A005_17-80.fits
Something went wrong with ORDER in combined/spex-sxd_cII-219_2017201002_2010A095_2060-2063comb.fits
Something went wrong with ORDER in combined/spex-prism_0218-3133_20091108_2009B009_101-114comb.fits
Something went wrong with ORDER in combined/spex-prism_lupus1539-3448_20090503_nan_1-16.fits
Something went wrong with ORDER in combined/spex-prism_J0422+1526_20101224_2010B015_110-115.fits
Something went wrong with ORDER in combined/spex-prism_1202-Marina_20090928_2009B053_91-98.fits
Something went wrong with ORDER in combined/spex-prism_V2675-Oph_20110331_nan_304-313comb.fits
Something went wrong with ORDER in combined/spex-prism_Brorfelde_2013201011_2010B071_65-84comb.fits
Something went wrong with ORDER in combined/spex-sxd_18-Ori_20090110_2008B083_173-260comb.fits
Something went wrong with ORDER in combined/spex-prism_2M-0850-02_2030201001_2009B069_152-161comb.fits
Something went wrong with ORDER in combined/spex-prism_filename_2010201011_2010B106_1-4comb.fits
Something went wrong with ORDER in combined/spex-prism_WISE-0821+1443_20101218_2010B095_77-82.fits
Something went wrong with ORDER in combined/spex-sxd_Titan_20090121_2008B068_178-183comb.fits
Something went wrong with ORDER in combined/spex-prism_taurus33-J044054+260117_20061118_2006B072_149-154comb.fits
Something went wrong with ORDER in combined/spex-sxd_taurus11-J041805+281502_20061118_2006B072_209-216comb.fits
Something went wrong with ORDER in combined/spex-sxd_LP-321-78_20110331_nan_110-117comb.fits
Something went wrong with ORDER in combined/spex-sxd_2MASS-1146216-2836570_20100126_2009B036_25-36.fits
Something went wrong with ORDER in combined/spex-sxd_2MASS-104552-6-281930-0_20100127_2009B036_19-42.fits
Something went wrong with ORDER in combined/spex-prism_CFHT-PL5_20100301_2010A067_3-10.fits
Something went wrong with ORDER in combined/spex-prism_IC348-034442+321039_20091002_2009B039_98-109comb.fits
Something went wrong with ORDER in combined/spex-prism_sn2010gd_20100717_2010A999_31-44comb.fits
Something went wrong with ORDER in combined/spex-sxd_J2233-2950_20100717_2010A999_328-335comb.fits
Something went wrong with ORDER in combined/spex-sxd_taurus26-J043254+242730_20061118_2006B072_181-186comb.fits
Something went wrong with ORDER in combined/spex-prism_J1425-3650_20100707_2010A999_43-48comb.fits
Something went wrong with ORDER in combined/spex-prism_2MASS-115321-7-401305-0_20100127_2009B036_65-74.fits
Something went wrong with ORDER in combined/spex-sxd_Titan_20100304_2010A024_7-12comb.fits
Something went wrong with ORDER in combined/spex-prism_2M-1154+22_2030201001_2009B069_282-301comb.fits
Something went wrong with ORDER in combined/spex-sxd_cII-239_2017201002_2010A095_2013-2014comb.fits
Something went wrong with ORDER in combined/spex-sxd_IRAS-04287+1801W_2014201001_2009B079_85-94comb.fits
Something went wrong with ORDER in combined/uspex-prism_SC183021+011134_20210829_2021B049_16-25comb.fits
Something went wrong with ORDER in combined/spex-longxd2.1_epsAur_20110330_nan_77-114comb.fits
Something went wrong with ORDER in combined/spex-prism_Lodieu-x2_20100910_2010B999_71-96.fits
Something went wrong with ORDER in combined/spex-prism_Magellan_20090109_2008B012_94-111comb.fits
Something went wrong with ORDER in combined/spex-prism_0337-1758_20091108_2009B009_157-164comb.fits
Something went wrong with ORDER in combined/spex-prism_AUR-79_2010201011_2010B106_145-154comb.fits
Something went wrong with ORDER in combined/spex-prism_695Bella_20100807_2010B035_66-69.fits
Something went wrong with ORDER in combined/spex-sxd_cII-229_2018201002_2010A095_3084-3089comb.fits
Something went wrong with ORDER in combined/spex-prism_J0433+2614_20101224_2010B015_269-276.fits
Something went wrong with ORDER in combined/spex-prism_AUR-84_2010201011_2010B106_57-66comb.fits
Something went wrong with ORDER in combined/spex-prism_Si2M54_20091031_2009B033_375-390comb.fits
Something went wrong with ORDER in combined/spex-prism_2335+1508_20091108_2009B009_23-30comb.fits
Something went wrong with ORDER in combined/spex-prism_NGC1333-032936+311750_20090928_2009B039_113-150.fits
Something went wrong with ORDER in combined/spex-prism_Tmove3-9879_20101005_2010B999_137-144.fits
Something went wrong with ORDER in combined/spex-prism_1381_20091109_2009B028_309-323comb.fits
Something went wrong with ORDER in combined/spex-prism_bd-ser-1_20090503_nan_81-88.fits
Something went wrong with ORDER in combined/spex-prism_107-Camilla_20090914_2009B105_17-36.fits
Something went wrong with ORDER in combined/spex-prism_NGC1333-032901+304915_20091002_2009B039_130-141comb.fits
Something went wrong with ORDER in combined/spex-prism_1049348-2706440_20100125_2009B036_27-32.fits
Something went wrong with ORDER in combined/spex-prism_660-Crescentia_20100613_2010A002_104-117.fits
Something went wrong with ORDER in combined/spex-prism_10179Ishigaki_20100807_2010B035_1-12.fits
Something went wrong with ORDER in combined/spex-prism_IC348-034153+315019_20091002_2009B039_86-97comb.fits
Something went wrong with ORDER in combined/spex-prism_IC348-034256+320428_20090927_2009B039_66-75.fits
Something went wrong with ORDER in combined/spex-sxd_IRASF-03300+3111_2014201001_2009B079_49-56comb.fits
Something went wrong with ORDER in combined/spex-sxd_CII-230_2016201002_2010A095_1119-1120comb.fits
Something went wrong with ORDER in combined/spex-prism_J1537-2054_20110331_nan_256-263comb.fits
Something went wrong with ORDER in combined/spex-prism_WISE0031_20101117_2010B095_27-36.fits
Something went wrong with ORDER in combined/spex-prism_Tm1-id140720_20100715_2010A999_45-52comb.fits
Something went wrong with ORDER in combined/spex-prism_IC348-034251+315629_20091002_2009B039_54-69comb.fits
Something went wrong with ORDER in combined/spex-prism_289-Nenetta_20090928_2009B053_27-34.fits
Something went wrong with ORDER in combined/spex-sxd_cII-029_2018201002_2010A095_3046-3049comb.fits
Something went wrong with ORDER in combined/spex-prism_SI2M-16_20091031_2009B033_351-358comb.fits
Something went wrong with ORDER in combined/spex-prism_DENIS-PJ1609-2345_20090404_2009A050_75-86.fits
Something went wrong with ORDER in combined/spex-sxd_eta-UMa_20090110_2008B083_437-456comb.fits
Something went wrong with ORDER in combined/spex-sxd_Titan_20100103_2009B012_7-12.fits
Something went wrong with ORDER in combined/spex-sxd_cII-275_2017201002_2010A095_2050-2051comb.fits
Something went wrong with ORDER in combined/spex-sxd_J2057-0252_20061118_2006B072_1-6comb.fits
Something went wrong with ORDER in combined/spex-sxd_cII-294_2018201002_2010A095_3014-3015comb.fits
Something went wrong with ORDER in combined/spex-prism_2MASS-1122175-302310B_20100125_2009B036_63-68.fits
Something went wrong with ORDER in combined/spex-prism_075259-4+413634-0_20100128_2009B036_21-26.fits
Something went wrong with ORDER in combined/spex-sxd_HOPS-301_20091231_2009B096_81-96.fits
Something went wrong with ORDER in combined/spex-prism_5392_2027201010_2010B049_1125-1132comb.fits
Something went wrong with ORDER in combined/spex-sxd_CII-177_2016201002_2010A095_1111-1112comb.fits
Something went wrong with ORDER in combined/spex-prism_2MASS-0150069-2940270_20100125_2009B036_45-50.fits
Something went wrong with ORDER in combined/spex-sxd_DU-Eri_20091122_2009B047_409-416comb.fits
Something went wrong with ORDER in combined/spex-sxd_cII-019_2017201002_2010A095_2114-2121comb.fits
Something went wrong with ORDER in combined/spex-prism_777-Gutemberga_20090928_2009B053_57-64.fits
Something went wrong with ORDER in combined/spex-prism_J1711+4028_20100707_2010A999_175-182comb.fits
Something went wrong with ORDER in combined/spex-sxd_EW-Lac_20091122_2009B047_277-296comb.fits
Something went wrong with ORDER in combined/spex-sxd_J2247-2952_20100717_2010A999_361-366comb.fits
Something went wrong with ORDER in combined/spex-prism_Kiuchi_20090801_nan_57-64comb.fits
Something went wrong with ORDER in combined/spex-prism_J2353-0833_20100707_2010A999_319-324comb.fits
Something went wrong with ORDER in combined/spex-sxd_Titan_20100131_2009B077_7-12comb.fits
Something went wrong with ORDER in combined/spex-prism_2000-PJ5_20090808_2009B055_2091-2100.fits
Something went wrong with ORDER in combined/spex-prism_2MASS0019262+461407_20091031_2009B033_318-325comb.fits
Something went wrong with ORDER in combined/spex-prism_4015-Wilson-Harrington_20090612_2009A005_131-200.fits
Something went wrong with ORDER in combined/spex-prism_CFHT-PL-6_20091031_2009B033_497-507comb.fits
Something went wrong with ORDER in combined/spex-sxd_J2201+2413_20100717_2010A999_373-380comb.fits
Something went wrong with ORDER in combined/spex-sxd_omi-Cas_20091122_2009B047_173-188comb.fits
Something went wrong with ORDER in combined/spex-prism_J0434+2445_20101224_2010B015_14-19.fits
Something went wrong with ORDER in combined/spex-sxd_HD-91120_20090110_2008B083_377-384comb.fits
Something went wrong with ORDER in combined/spex-sxd_2MASS-110750-3-342100_20100126_2009B036_51-56.fits
Something went wrong with ORDER in combined/spex-prism_SIMP-J1307298-055814_20110331_nan_168-179comb.fits
Something went wrong with ORDER in combined/spex-prism_2M-1034+20_2030201001_2009B069_214-221comb.fits
Something went wrong with ORDER in combined/spex-prism_LP-321-78-B_20110331_nan_101-108comb.fits
Something went wrong with ORDER in combined/spex-prism_AMUN_20100201_2009B074_203-226comb.fits
Something went wrong with ORDER in combined/spex-sxd_LkCa-21_2006201001_2009B086_138-145comb.fits
Something went wrong with ORDER in combined/spex-sxd_IRAS-03220+3035-S_2014201001_2009B079_11-12comb.fits
Something went wrong with ORDER in combined/spex-prism_LP764-40B_20061118_2006B072_22-27comb.fits
Something went wrong with ORDER in combined/spex-prism_21-Lutetia_20090107_2008B006_87-236comb.fits
Something went wrong with ORDER in combined/spex-sxd_J0539+0407_20090110_2008B083_221-244comb.fits
Something went wrong with ORDER in combined/spex-sxd_CY-Tau_20090105_2008B050_322-331comb.fits
Something went wrong with ORDER in combined/spex-prism_IC348-034530+313739_20090927_2009B039_58-65.fits
Something went wrong with ORDER in combined/spex-prism_137062-1998-WM_2015201010_2010B046_124-167comb.fits
Something went wrong with ORDER in combined/spex-prism_2000-CO101_20091003_2009B074_31-34.fits
Something went wrong with ORDER in combined/spex-prism_J1935-2846_20100707_2010A999_217-224comb.fits
Something went wrong with ORDER in combined/spex-sxd_042636-5-+243946-9_20090116_2008B999_21-22comb.fits
Something went wrong with ORDER in combined/spex-prism_P-2010H2_20100422_2010A999_9-24.fits
Something went wrong with ORDER in combined/spex-sxd_HBC-388_20090104_2008B050_138-179comb.fits
Something went wrong with ORDER in combined/spex-prism_IC348-034410+313238_20090927_2009B039_92-101.fits
Something went wrong with ORDER in combined/spex-prism_sd2-11346_20101112_2010B999_30-37comb.fits
Something went wrong with ORDER in combined/spex-prism_327-Columbia_20090914_2009B105_200-233.fits
Something went wrong with ORDER in combined/spex-prism_sn2009dc_20090522_nan_1-62comb.fits
Something went wrong with ORDER in combined/spex-prism_J1246+5353_20100717_2010A999_37-42comb.fits
Something went wrong with ORDER in combined/spex-longxd2.3_V1247-Ori_20100228_2010A024_370-409comb.fits
Something went wrong with ORDER in combined/spex-sxd_Titan_20090120_2008B020_168-173comb.fits
Something went wrong with ORDER in combined/spex-prism_AUR-BD03_2010201011_2010B106_83-98comb.fits
Something went wrong with ORDER in combined/spex-prism_CFHT-PL2_2030201001_2009B069_77-86comb.fits
Something went wrong with ORDER in combined/spex-prism_2003-XF11_20100224_2010A029_35-58.fits
Something went wrong with ORDER in combined/spex-sxd_Titan_20100723_2010A056_7-12.fits
Something went wrong with ORDER in combined/spex-prism_IC348-034302+314436_20090927_2009B039_1-10.fits
Something went wrong with ORDER in combined/spex-prism_1101-Clematis_20090928_2009B053_11-18.fits
Something went wrong with ORDER in combined/spex-sxd_cII-239_2018201002_2010A095_3024-3025comb.fits
Something went wrong with ORDER in combined/spex-prism_TWA-30B_20100128_2009B036_27-44.fits
Something went wrong with ORDER in combined/spex-sxd_IRAS-16442-0930_20090414_nan_21-28.fits
Something went wrong with ORDER in combined/spex-prism_WISE-0714-1212_20101218_2010B095_53-58.fits
Something went wrong with ORDER in combined/spex-prism_J2341-1133_20100707_2010A999_291-296comb.fits
Something went wrong with ORDER in combined/spex-prism_48732_20091109_2009B028_263-264comb.fits
Something went wrong with ORDER in combined/spex-sxd_HBC-392_20091231_2009B096_17-32.fits
Something went wrong with ORDER in combined/spex-prism_Krauss-2_20091031_2009B033_516-517comb.fits
Something went wrong with ORDER in combined/spex-prism_SN-2010ai_20100327_2010A998_19-32comb.fits
Something went wrong with ORDER in combined/spex-sxd_cII-270_2018201002_2010A095_3097-3098comb.fits

,OBSERVER,OBJECT,RA,DEC,SRT_MJD,END_MJD,MODE,SRT_AM,END_AM,SRT_TIME,END_DATE,ORDER,YUNITS,TC_STDID,TC_STDST,OBJECT_TYPE
0,"E Hesselbach, K. Bjorkman",phi Per,+01:43:38.70,++50:41:22.3,54841.342851,54841.34587,ShortXD,1.585,1.608,08:13:42.334733,2009-01-10,None,W m-2 um-1,HD12365,A0V,Fixed
1,Your_Name,2mass 0850+10: L/T binary,08:50:35.28,+10:57:15.5,54057.612701,54057.624472,LowRes15,1.025,1.016,14:42:17.386584,2006-11-18,None,W m-2 um-1,hd 74721,A0V,Fixed
2,Your_Name,redred-id80435,+12:54:38.19,++43:46:54.2,55394.240318,55394.255071,LowRes15,1.24,1.299,05:46:03.469897,2010-07-17,None,W m-2 um-1,HD 109615,A0V,Fixed
3,"E Hesselbach, K. Bjorkman",delta Sco,+16:00:20.46,-22:37:19.5,54841.637731,54841.638719,ShortXD,2.777,2.744,15:18:19.967282,2009-01-10,None,W m-2 um-1,HD 131951,A0V,Fixed
4,"E Hesselbach, K. Bjorkman",V838 Mon,+07:04:04.47,-03:50:53.9,54841.469131,54841.482366,ShortXD,1.147,1.184,11:15:32.942429,2009-01-10,None,W m-2 um-1,HD 50931,A0V,Fixed
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
534,"Vishnu Reddy, Will Swearson",423 Diotima,+04:27:28.78,++17:18:08.3,55088.535633,55088.593854,LowRes15,1.201,1.031,12:51:18.722121,2009-09-14,None,DN s-1,SAO 93936,G2+V,Moving
535,Looper,TWA 30B,+11:32:17.96,-30:18:23.2,55223.634022,55223.651826,LowRes15,1.808,1.971,15:12:59.466583,2010-01-27,None,DN s-1,HD 98949,A0V,Moving
536,Your_Name,bPic13774,+22:17:16.77,++23:09:26.1,55394.645792,55394.646745,ShortXD,1.23,1.234,15:29:56.464737,2010-07-17,None,W m-2 um-1,HD 212643,A0V,Fixed
537,"E Hesselbach, K. Bjorkman",nu Gem,+06:28:57.19,++20:12:43.1,54841.499811,54841.504701,ShortXD,1.219,1.245,11:59:43.651338,2009-01-10,None,W m-2 um-1,HD 43583,A0V,Fixed
538,Your_Name,ID 202132,+03:37:03.37,-30:42:34.5,55474.585516,55474.592237,ShortXD,1.644,1.67,14:03:08.594008,2010-10-05,None,DN s-1,tau For (std),A0V,Moving

In [28]:
MASTER_DF

Empty DataFrame
Columns: []
Index: []